% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Women's Basketball March Madness: Bradley-Terry Model Analysis},
  pdfauthor={Kalynn Willis, Jasmine, Ellie},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Women's Basketball March Madness: Bradley-Terry Model Analysis}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Analyzing Mid-Tier Seed (8-12) Advancement Probabilities}
\author{Kalynn Willis, Jasmine, Ellie}
\date{2025-11-01}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{3}
\tableofcontents
}
\section*{Executive Summary}\label{executive-summary}
\addcontentsline{toc}{section}{Executive Summary}

Every March, the NCAA Women's Basketball Tournament captures national
attention with underdog stories. But in 2023 and 2024, something unusual
happened: not a single mid-tier team---those seeded 8 through 12---made
it to the Sweet Sixteen. Were these back-to-back ``chalk'' tournaments
(where favorites win) a statistical fluke, or should we expect this
regularly?

This study examines middle-seeded teams in March Madness to answer:
\textbf{How often do 8-12 seeds make deep runs, and which ones should we
watch most closely?}

We analyzed over 5,000 regular season games across 5 seasons to create
strength ratings for all tournament teams---accounting for who you
played and how you performed against them, not just wins and losses. We
then simulated the entire tournament 5,000 times to see what typically
happens to teams seeded 8-12.

\subsection{Main Findings}\label{main-findings}

In a typical tournament, expect about \textbf{two to three teams} seeded
8-12 to reach the Sweet Sixteen. Our simulations show an average of 2.36
teams (range 0-7), with most tournaments having 1-3 mid-tier seeds
advance. The 2023-2024 drought (zero advancing) has about a \textbf{6\%
chance} of happening---genuinely unusual, occurring naturally about once
every \textbf{17 years}, not every tournament cycle.

When a mid-tier seed breaks through to the Sweet Sixteen, what happens
next? About one in five reach the Final Four, and only one in
thirty-eight win the championship. Making the Sweet Sixteen is the
hardest part; once there, they're competitive (48.6\% reach Elite 8) but
still face long odds against top seeds for the title.

Perhaps most importantly, seed numbers don't tell the whole story.
Within the 8-12 seed range, team strength (Bradley-Terry λ values)
varies dramatically. The strongest mid-tier seeds can have Sweet Sixteen
probabilities near 20\%, while the weakest approach zero. The
difference? Teams with exceptionally strong regular season performance
earn better odds regardless of their seed number. Looking beyond seed
numbers to actual team strength separates informed predictions from
guesswork.

\textbf{Key Numbers:}

\begin{itemize}
\tightlist
\item
  \textbf{Expected 8-12 seeds in Sweet 16:} 2.36 teams (simulation
  average, range 0-7)
\item
  \textbf{Conditional probability of reaching Finals (given Sweet 16):}
  5.3\%
\item
  \textbf{Conditional probability of winning championship (given Sweet
  16):} 1.9\%
\item
  \textbf{Highest Sweet 16 probability (among mid-tier seeds):} Iowa
  State Cyclones (8-seed) at 17.2\%
\item
  \textbf{Probability of zero 8-12 seeds in Sweet 16:} 5.94\% (about
  1-in-17 tournaments)
\end{itemize}

\subsection{What This Means}\label{what-this-means}

\textbf{For bracket predictions:} Be conservative with upset picks.
Expecting five or six mid-tier seeds in the Sweet Sixteen is overly
optimistic. Expect 2-3 seeds to advance, with most tournaments having
1-3. Focus on teams with high λ values (strong regular season
performance) rather than hoping for multiple Cinderella stories.

\textbf{For coaches and teams:} Regular season success translates
directly to tournament opportunity. Strong performance against quality
opponents measurably improves your chances, even with a middling seed.
The difference between the strongest and weakest 8-12 seeds is
substantial---ranging from \textasciitilde18\% Sweet 16 probability down
to near-zero.

\textbf{For fans and media:} When a 10-seed reaches the Elite Eight,
celebrate appropriately. It's genuinely rare. The 2023-2024 drought of
zero mid-tier seeds advancing was even rarer---a 1-in-17 occurrence that
won't happen frequently.

\subsection{The Bottom Line}\label{the-bottom-line}

The past two tournaments showed what happens when favorites dominate at
a historically unusual level. Mid-tier seeds will break through
again---in fact, 2-3 typically do each year. Understanding individual
team strength, beyond just seed numbers, helps identify those
breakthrough candidates. Basketball remains beautifully unpredictable,
but patterns emerge. Expect about two to three mid-tier seeds to reach
the Sweet Sixteen in most years, with about half of those making deeper
runs to the Elite Eight.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{1. Introduction}\label{introduction}

\subsection{1.1 Motivation and Problem
Statement}\label{motivation-and-problem-statement}

The NCAA Division I Women's Basketball Tournament, colloquially known as
``March Madness,'' is an annual single-elimination tournament featuring
64 teams seeded 1-16 across four regional brackets. Understanding
tournament dynamics---particularly the advancement patterns of mid-tier
seeds---has practical value for:

\begin{itemize}
\tightlist
\item
  \textbf{Sports Analytics:} Quantifying competitive balance and upset
  potential
\item
  \textbf{Bracket Prediction:} Informed probabilistic forecasting
\item
  \textbf{Team Evaluation:} Identifying over/under-seeded teams
\item
  \textbf{Media and Fans:} Setting appropriate expectations for underdog
  stories
\end{itemize}

\subsection{1.2 Why Focus on 8-12 Seeds?}\label{why-focus-on-8-12-seeds}

Seeds 8-12 occupy a strategic middle ground in tournament analysis:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Not Automatic Exits:} Unlike 13-16 seeds (which rarely win
  first-round games), 8-12 seeds have realistic chances to win at least
  one game
\item
  \textbf{Not Overwhelming Favorites:} Unlike 1-4 seeds (which typically
  dominate early rounds), 8-12 seeds face genuine competitive challenges
\item
  \textbf{Upset Potential:} These teams represent the ``Cinderella''
  sweet spot---capable of deep runs but facing long odds
\item
  \textbf{Practical Relevance:} Understanding this tier helps calibrate
  reasonable expectations vs.~hype
\end{enumerate}

\subsection{1.3 Research Questions}\label{research-questions}

This analysis addresses two primary research questions:

\textbf{Research Question 1:} How many of the 8-12 seeds should we
expect to advance past the second round (to the Sweet 16)?

\textbf{Research Question 2:} Given that a team seeded 8-12 advanced
past the second round, what is the probability they reach the finals or
win the championship?

Additionally, we extend the analysis to:

\begin{itemize}
\tightlist
\item
  Calculate \textbf{individual team probabilities} for each specific
  8-12 seed
\item
  Contextualize the 2023-2024 historical outcome (zero 8-12 seeds in
  Sweet 16)
\item
  Validate analytical predictions with Monte Carlo simulation
\end{itemize}

\subsection{1.4 Historical Context}\label{historical-context}

In both the 2023 and 2024 NCAA Women's Basketball Tournaments,
\textbf{no teams seeded 8-12 reached the Sweet 16}. This unprecedented
back-to-back occurrence motivates our analysis: Is this outcome
statistically unusual, or should we expect such scenarios regularly?

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{2. Methodology}\label{methodology}

\subsection{2.1 Bradley-Terry Model
Framework}\label{bradley-terry-model-framework}

\subsubsection{Model Specification}\label{model-specification}

The Bradley-Terry model is a probabilistic framework for modeling
pairwise comparisons. For teams \(i\) and \(j\) with latent strength
parameters \(\lambda_i\) and \(\lambda_j\), the probability that team
\(i\) defeats team \(j\) is:

\[
P(\text{team } i \text{ beats team } j) = \frac{e^{\lambda_i}}{e^{\lambda_i} + e^{\lambda_j}} = \frac{1}{1 + e^{-(\lambda_i - \lambda_j)}}
\]

\textbf{Key Properties:}

\begin{itemize}
\tightlist
\item
  \(\lambda_i\) represents the log-strength of team \(i\)
\item
  Higher \(\lambda\) indicates stronger team
\item
  The model is invariant to additive constants (we fix one reference
  team at \(\lambda = 0\))
\item
  Win probability depends only on the \textbf{difference}
  \(\lambda_i - \lambda_j\)
\end{itemize}

\subsubsection{Advantages for Tournament
Analysis}\label{advantages-for-tournament-analysis}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Handles incomplete matchups:} Not every team plays every other
  team
\item
  \textbf{Strength transitivity:} If A beats B and B beats C, model
  appropriately adjusts A's advantage over C
\item
  \textbf{Uncertainty quantification:} Standard errors on \(\lambda\)
  estimates allow confidence intervals
\item
  \textbf{Probabilistic predictions:} Naturally produces win
  probabilities for any matchup
\end{enumerate}

\subsubsection{Model Fitting}\label{model-fitting}

We fit the Bradley-Terry model using maximum likelihood estimation via
the \texttt{BradleyTerry2} R package. The log-likelihood for \(n\) games
is:

\[
\ell(\lambda) = \sum_{k=1}^{n} \left[ \lambda_{i_k} - \log(e^{\lambda_{i_k}} + e^{\lambda_{j_k}}) \right]
\]

where game \(k\) was won by team \(i_k\) over team \(j_k\).

We fit \textbf{separate Bradley-Terry models for each season}, then
aggregate results using inverse-variance weighting. This approach
accounts for year-to-year variation while providing stable estimates:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# From scripts/02\_bradley\_terry\_model.R}

\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{require}\NormalTok{(}\StringTok{"BradleyTerry2"}\NormalTok{)) \{}
    \FunctionTok{install.packages}\NormalTok{(}\StringTok{"BradleyTerry2"}\NormalTok{)}
    \FunctionTok{library}\NormalTok{(BradleyTerry2)}
\NormalTok{\}}

\NormalTok{bt\_data }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\FunctionTok{here}\NormalTok{(}\StringTok{"data"}\NormalTok{, }\StringTok{"processed"}\NormalTok{, }\StringTok{"bt\_data.rds"}\NormalTok{))}
\NormalTok{tournament\_seeds }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\FunctionTok{here}\NormalTok{(}\StringTok{"data"}\NormalTok{, }\StringTok{"processed"}\NormalTok{, }\StringTok{"tournament\_seeds.rds"}\NormalTok{))}

\CommentTok{\# Fit separate models for each season}
\NormalTok{seasons }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(}\FunctionTok{unique}\NormalTok{(bt\_data}\SpecialCharTok{$}\NormalTok{season))}
\NormalTok{all\_season\_abilities }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{()}

\ControlFlowTok{for}\NormalTok{ (season\_year }\ControlFlowTok{in}\NormalTok{ seasons) \{}
\NormalTok{    bt\_season }\OtherTok{\textless{}{-}}\NormalTok{ bt\_data }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(season }\SpecialCharTok{==}\NormalTok{ season\_year)}

    \CommentTok{\# Fit Bradley{-}Terry model for this season}
\NormalTok{    bt\_model\_season }\OtherTok{\textless{}{-}}\NormalTok{ BradleyTerry2}\SpecialCharTok{::}\FunctionTok{BTm}\NormalTok{(}
        \AttributeTok{outcome =} \FunctionTok{cbind}\NormalTok{(home.wins, away.wins),}
        \AttributeTok{player1 =}\NormalTok{ home.team,}
        \AttributeTok{player2 =}\NormalTok{ away.team,}
        \AttributeTok{formula =} \SpecialCharTok{\textasciitilde{}}\NormalTok{ team }\SpecialCharTok{+}\NormalTok{ home\_adv\_bar,}
        \AttributeTok{id =} \StringTok{"team"}\NormalTok{,}
        \AttributeTok{contrasts =} \FunctionTok{list}\NormalTok{(}\AttributeTok{team =} \StringTok{"contr.sum"}\NormalTok{),}
        \AttributeTok{data =}\NormalTok{ bt\_season}
\NormalTok{    )}

    \CommentTok{\# Extract abilities}
\NormalTok{    abilities\_season }\OtherTok{\textless{}{-}}\NormalTok{ BradleyTerry2}\SpecialCharTok{::}\FunctionTok{BTabilities}\NormalTok{(bt\_model\_season)}
\NormalTok{    abilities\_df }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(abilities\_season) }\SpecialCharTok{\%\textgreater{}\%}
        \FunctionTok{rownames\_to\_column}\NormalTok{(}\AttributeTok{var =} \StringTok{"team"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
        \FunctionTok{as\_tibble}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
        \FunctionTok{rename}\NormalTok{(}\AttributeTok{lambda =}\NormalTok{ ability, }\AttributeTok{se =}\NormalTok{ s.e.) }\SpecialCharTok{\%\textgreater{}\%}
        \FunctionTok{mutate}\NormalTok{(}\AttributeTok{season =}\NormalTok{ season\_year)}

\NormalTok{    all\_season\_abilities[[}\FunctionTok{as.character}\NormalTok{(season\_year)]] }\OtherTok{\textless{}{-}}\NormalTok{ abilities\_df}

    \CommentTok{\# Convergence checks}
    \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\NormalTok{bt\_model\_season}\SpecialCharTok{$}\NormalTok{converged) \{}
        \FunctionTok{stop}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"Model FAILED TO CONVERGE for \%d season"}\NormalTok{, season\_year))}
\NormalTok{    \}}
\NormalTok{\}}

\CommentTok{\# Combine all seasons\textquotesingle{} abilities}
\NormalTok{all\_abilities }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(all\_season\_abilities)}

\CommentTok{\# Z{-}score within season (CRITICAL: Each season\textquotesingle{}s BT is identified up to a shift)}
\NormalTok{all\_abilities\_scaled }\OtherTok{\textless{}{-}}\NormalTok{ all\_abilities }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(season) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}
        \AttributeTok{season\_sd =} \FunctionTok{sd}\NormalTok{(lambda, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
        \AttributeTok{season\_mean =} \FunctionTok{mean}\NormalTok{(lambda, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
        \AttributeTok{lambda\_z =}\NormalTok{ (lambda }\SpecialCharTok{{-}}\NormalTok{ season\_mean) }\SpecialCharTok{/}\NormalTok{ season\_sd,}
        \AttributeTok{se\_z =}\NormalTok{ se }\SpecialCharTok{/}\NormalTok{ season\_sd,}
        \AttributeTok{se\_z =} \FunctionTok{pmax}\NormalTok{(se\_z, }\FloatTok{1e{-}6}\NormalTok{)}
\NormalTok{    ) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ungroup}\NormalTok{()}

\CommentTok{\# Aggregate z{-}scored abilities using inverse{-}variance weighting}
\NormalTok{team\_abilities\_df }\OtherTok{\textless{}{-}}\NormalTok{ all\_abilities\_scaled }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(team) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}
        \AttributeTok{lambda =} \FunctionTok{weighted.mean}\NormalTok{(lambda\_z, }\AttributeTok{w =} \DecValTok{1} \SpecialCharTok{/}\NormalTok{ (se\_z}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{), }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
        \AttributeTok{se =} \FunctionTok{sqrt}\NormalTok{(}\DecValTok{1} \SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(}\DecValTok{1} \SpecialCharTok{/}\NormalTok{ (se\_z}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{), }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)),}
        \AttributeTok{n\_seasons =} \FunctionTok{n}\NormalTok{(),}
        \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{    ) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(lambda))}

\CommentTok{\# Add tournament seeding information}
\NormalTok{team\_abilities\_with\_seeds }\OtherTok{\textless{}{-}}\NormalTok{ team\_abilities\_df }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{left\_join}\NormalTok{(tournament\_seeds }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(team, seed, region), }\AttributeTok{by =} \StringTok{"team"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}
        \AttributeTok{is\_mid\_tier\_seed =} \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(seed) }\SpecialCharTok{\&}\NormalTok{ seed }\SpecialCharTok{\textgreater{}=} \DecValTok{8} \SpecialCharTok{\&}\NormalTok{ seed }\SpecialCharTok{\textless{}=} \DecValTok{12}\NormalTok{,}
        \AttributeTok{seed\_category =} \FunctionTok{case\_when}\NormalTok{(}
            \FunctionTok{is.na}\NormalTok{(seed) }\SpecialCharTok{\textasciitilde{}} \StringTok{"Non{-}tournament"}\NormalTok{,}
\NormalTok{            seed }\SpecialCharTok{\textless{}=} \DecValTok{4} \SpecialCharTok{\textasciitilde{}} \StringTok{"1{-}4 seeds"}\NormalTok{,}
\NormalTok{            seed }\SpecialCharTok{\textless{}=} \DecValTok{7} \SpecialCharTok{\textasciitilde{}} \StringTok{"5{-}7 seeds"}\NormalTok{,}
\NormalTok{            seed }\SpecialCharTok{\textless{}=} \DecValTok{12} \SpecialCharTok{\textasciitilde{}} \StringTok{"8{-}12 seeds"}\NormalTok{,}
            \ConstantTok{TRUE} \SpecialCharTok{\textasciitilde{}} \StringTok{"13{-}16 seeds"}
\NormalTok{        )}
\NormalTok{    )}

\CommentTok{\# Compute win probability matrix (neutral site)}
\NormalTok{lambda\_vec }\OtherTok{\textless{}{-}} \FunctionTok{setNames}\NormalTok{(team\_abilities\_df}\SpecialCharTok{$}\NormalTok{lambda, team\_abilities\_df}\SpecialCharTok{$}\NormalTok{team)}
\NormalTok{lambda\_diff }\OtherTok{\textless{}{-}} \FunctionTok{outer}\NormalTok{(}\AttributeTok{X =}\NormalTok{ lambda\_vec, }\AttributeTok{Y =}\NormalTok{ lambda\_vec, }\AttributeTok{FUN =} \StringTok{"{-}"}\NormalTok{)}
\NormalTok{win\_probs }\OtherTok{\textless{}{-}} \DecValTok{1} \SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{+} \FunctionTok{exp}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{1} \SpecialCharTok{*}\NormalTok{ lambda\_diff))}
\NormalTok{win\_probs }\OtherTok{\textless{}{-}} \FunctionTok{pmin}\NormalTok{(}\FunctionTok{pmax}\NormalTok{(win\_probs, }\FloatTok{1e{-}6}\NormalTok{), }\DecValTok{1} \SpecialCharTok{{-}} \FloatTok{1e{-}6}\NormalTok{) }\CommentTok{\# Numerical stability}
\FunctionTok{diag}\NormalTok{(win\_probs) }\OtherTok{\textless{}{-}} \ConstantTok{NA}

\CommentTok{\# Save results}
\FunctionTok{saveRDS}\NormalTok{(bt\_model\_season, }\FunctionTok{here}\NormalTok{(}\StringTok{"data"}\NormalTok{, }\StringTok{"processed"}\NormalTok{, }\StringTok{"bt\_model.rds"}\NormalTok{))}
\FunctionTok{saveRDS}\NormalTok{(team\_abilities\_with\_seeds, }\FunctionTok{here}\NormalTok{(}\StringTok{"data"}\NormalTok{, }\StringTok{"processed"}\NormalTok{, }\StringTok{"team\_abilities\_with\_seeds.rds"}\NormalTok{))}
\FunctionTok{saveRDS}\NormalTok{(win\_probs, }\FunctionTok{here}\NormalTok{(}\StringTok{"data"}\NormalTok{, }\StringTok{"processed"}\NormalTok{, }\StringTok{"win\_probability\_matrix.rds"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\subsection{2.2 Data}\label{data}

\subsubsection{Data Source and
Collection}\label{data-source-and-collection}

\textbf{Source:} Women's NCAA Basketball data via the \texttt{wehoop} R
package

\textbf{Scope:} Regular season games from 2019, 2021-2024 seasons (5
seasons total) - Note: 2020 season excluded due to COVID-19 disruptions
- Multi-season data provides more robust team strength estimates -
Separate Bradley-Terry models fit per season, then aggregated

\textbf{Dataset Statistics:}

\begin{itemize}
\tightlist
\item
  Total teams analyzed: 353
\item
  Total games: 22929
\item
  Tournament teams: 64
\item
  Teams with 8-12 seeds: 20
\end{itemize}

\subsubsection{Data Collection Process}\label{data-collection-process}

We begin by loading game schedules for five seasons (2019, 2021-2024).
The \texttt{wehoop} package provides comprehensive game-level data from
ESPN, including scores, dates, and team identifiers.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# From scripts/01\_data\_collection\_UPDATED.R}
\FunctionTok{suppressPackageStartupMessages}\NormalTok{(\{}
    \FunctionTok{library}\NormalTok{(tidyverse)}
    \FunctionTok{library}\NormalTok{(lubridate)}
    \FunctionTok{library}\NormalTok{(here)}
\NormalTok{\})}

\CommentTok{\# Expanded to include more seasons for more robust model estimation}
\CommentTok{\# Using 2019{-}2024 (5 seasons) {-} skipping 2020 due to COVID disruptions}
\NormalTok{SEASONS }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{2019}\NormalTok{, }\DecValTok{2021}\NormalTok{, }\DecValTok{2022}\NormalTok{, }\DecValTok{2023}\NormalTok{, }\DecValTok{2024}\NormalTok{)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{479}\NormalTok{)}

\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{requireNamespace}\NormalTok{(}\StringTok{"wehoop"}\NormalTok{, }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{)) \{}
    \FunctionTok{install.packages}\NormalTok{(}\StringTok{"wehoop"}\NormalTok{)}
\NormalTok{\}}
\FunctionTok{library}\NormalTok{(wehoop)}

\CommentTok{\# Helper function to pick first available column name}
\NormalTok{pick\_first }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(cands, nm) \{}
\NormalTok{    hit }\OtherTok{\textless{}{-}} \FunctionTok{intersect}\NormalTok{(cands, nm)}
    \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(hit)) hit[}\DecValTok{1}\NormalTok{] }\ControlFlowTok{else} \ConstantTok{NA\_character\_}
\NormalTok{\}}

\NormalTok{raw }\OtherTok{\textless{}{-}}\NormalTok{ wehoop}\SpecialCharTok{::}\FunctionTok{load\_wbb\_schedule}\NormalTok{(}\AttributeTok{seasons =}\NormalTok{ SEASONS)}
\FunctionTok{stopifnot}\NormalTok{(}\FunctionTok{is.data.frame}\NormalTok{(raw), }\FunctionTok{nrow}\NormalTok{(raw) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{)}

\NormalTok{nm }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(raw)}

\CommentTok{\# Dates / IDs / season}
\NormalTok{date\_col }\OtherTok{\textless{}{-}} \FunctionTok{pick\_first}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"game\_date"}\NormalTok{, }\StringTok{"start\_date"}\NormalTok{, }\StringTok{"date"}\NormalTok{), nm)}
\NormalTok{season\_col }\OtherTok{\textless{}{-}} \FunctionTok{pick\_first}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"season"}\NormalTok{, }\StringTok{"season\_year"}\NormalTok{), nm)}
\NormalTok{id\_col }\OtherTok{\textless{}{-}} \FunctionTok{pick\_first}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"game\_id"}\NormalTok{, }\StringTok{"id"}\NormalTok{, }\StringTok{"espn\_game\_id"}\NormalTok{), nm)}

\NormalTok{home\_team\_col }\OtherTok{\textless{}{-}} \FunctionTok{pick\_first}\NormalTok{(}\FunctionTok{c}\NormalTok{(}
    \StringTok{"home\_display\_name"}\NormalTok{, }\StringTok{"home\_name"}\NormalTok{, }\StringTok{"home\_location"}\NormalTok{, }\StringTok{"home\_short\_display\_name"}\NormalTok{,}
    \StringTok{"home\_team"}\NormalTok{, }\StringTok{"home\_team\_name"}\NormalTok{, }\StringTok{"home\_team\_display\_name"}
\NormalTok{), nm)}

\NormalTok{away\_team\_col }\OtherTok{\textless{}{-}} \FunctionTok{pick\_first}\NormalTok{(}\FunctionTok{c}\NormalTok{(}
    \StringTok{"away\_display\_name"}\NormalTok{, }\StringTok{"away\_name"}\NormalTok{, }\StringTok{"away\_location"}\NormalTok{, }\StringTok{"away\_short\_display\_name"}\NormalTok{,}
    \StringTok{"away\_team"}\NormalTok{, }\StringTok{"away\_team\_name"}\NormalTok{, }\StringTok{"away\_team\_display\_name"}
\NormalTok{), nm)}

\NormalTok{home\_score\_col }\OtherTok{\textless{}{-}} \FunctionTok{pick\_first}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"home\_score"}\NormalTok{, }\StringTok{"home\_points"}\NormalTok{, }\StringTok{"home\_team\_score"}\NormalTok{), nm)}
\NormalTok{away\_score\_col }\OtherTok{\textless{}{-}} \FunctionTok{pick\_first}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"away\_score"}\NormalTok{, }\StringTok{"away\_points"}\NormalTok{, }\StringTok{"away\_team\_score"}\NormalTok{), nm)}

\NormalTok{neutral\_col }\OtherTok{\textless{}{-}} \FunctionTok{pick\_first}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"neutral\_site"}\NormalTok{, }\StringTok{"neutral"}\NormalTok{, }\StringTok{"is\_neutral\_site"}\NormalTok{), nm)}
\NormalTok{type\_col }\OtherTok{\textless{}{-}} \FunctionTok{pick\_first}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"season\_type"}\NormalTok{, }\StringTok{"game\_type"}\NormalTok{, }\StringTok{"tournament\_type"}\NormalTok{), nm)}

\NormalTok{must\_have }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(date\_col, season\_col, home\_team\_col, away\_team\_col)}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{any}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(must\_have))) \{}
    \FunctionTok{stop}\NormalTok{(}\StringTok{"Critical columns missing after remapping."}\NormalTok{)}
\NormalTok{\}}

\NormalTok{games\_combined }\OtherTok{\textless{}{-}}\NormalTok{ raw }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{transmute}\NormalTok{(}
        \AttributeTok{game\_id =} \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(id\_col)) }\FunctionTok{as.character}\NormalTok{(.data[[id\_col]]) }\ControlFlowTok{else} \ConstantTok{NA\_character\_}\NormalTok{,}
        \AttributeTok{season =} \FunctionTok{suppressWarnings}\NormalTok{(}\FunctionTok{as.integer}\NormalTok{(.data[[season\_col]])),}
        \AttributeTok{game\_date =} \FunctionTok{suppressWarnings}\NormalTok{(lubridate}\SpecialCharTok{::}\FunctionTok{ymd}\NormalTok{(.data[[date\_col]])),}
        \AttributeTok{home\_team =} \FunctionTok{as.character}\NormalTok{(.data[[home\_team\_col]]),}
        \AttributeTok{away\_team =} \FunctionTok{as.character}\NormalTok{(.data[[away\_team\_col]]),}
        \AttributeTok{home\_score =} \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(home\_score\_col)) \{}
            \FunctionTok{suppressWarnings}\NormalTok{(}\FunctionTok{as.integer}\NormalTok{(.data[[home\_score\_col]]))}
\NormalTok{        \} }\ControlFlowTok{else}\NormalTok{ \{}
            \ConstantTok{NA\_integer\_}
\NormalTok{        \},}
        \AttributeTok{away\_score =} \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(away\_score\_col)) \{}
            \FunctionTok{suppressWarnings}\NormalTok{(}\FunctionTok{as.integer}\NormalTok{(.data[[away\_score\_col]]))}
\NormalTok{        \} }\ControlFlowTok{else}\NormalTok{ \{}
            \ConstantTok{NA\_integer\_}
\NormalTok{        \},}
        \AttributeTok{neutral\_site =} \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(neutral\_col)) \{}
\NormalTok{            val }\OtherTok{\textless{}{-}}\NormalTok{ .data[[neutral\_col]]}
            \FunctionTok{as.integer}\NormalTok{(val }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\ConstantTok{TRUE}\NormalTok{, }\DecValTok{1}\NormalTok{, }\StringTok{"1"}\NormalTok{, }\StringTok{"TRUE"}\NormalTok{, }\StringTok{"True"}\NormalTok{, }\StringTok{"true"}\NormalTok{))}
\NormalTok{        \} }\ControlFlowTok{else}\NormalTok{ \{}
            \DecValTok{0}\DataTypeTok{L}
\NormalTok{        \},}
        \AttributeTok{season\_type =} \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(type\_col)) .data[[type\_col]] }\ControlFlowTok{else} \ConstantTok{NA}
\NormalTok{    ) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{distinct}\NormalTok{(game\_id, }\AttributeTok{.keep\_all =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

After loading, we apply D-I team normalization \textbf{before any
filtering} (critical fix), then filter for data quality:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# From scripts/01\_data\_collection\_UPDATED.R (continued)}

\CommentTok{\# ====== D{-}I NORMALIZATION (BEFORE ANY FILTERING) ======}
\NormalTok{normalize\_name }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) stringr}\SpecialCharTok{::}\FunctionTok{str\_squish}\NormalTok{(stringr}\SpecialCharTok{::}\FunctionTok{str\_to\_lower}\NormalTok{(x))}

\NormalTok{d1\_teams }\OtherTok{\textless{}{-}} \FunctionTok{tryCatch}\NormalTok{(}
    \FunctionTok{suppressMessages}\NormalTok{(purrr}\SpecialCharTok{::}\FunctionTok{map\_dfr}\NormalTok{(SEASONS, wehoop}\SpecialCharTok{::}\NormalTok{espn\_wbb\_teams)),}
    \AttributeTok{error =} \ControlFlowTok{function}\NormalTok{(e) }\ConstantTok{NULL}
\NormalTok{)}

\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{is.null}\NormalTok{(d1\_teams) }\SpecialCharTok{||} \SpecialCharTok{!}\StringTok{"team\_id"} \SpecialCharTok{\%in\%} \FunctionTok{names}\NormalTok{(d1\_teams)) \{}
\NormalTok{    games\_norm }\OtherTok{\textless{}{-}}\NormalTok{ games\_combined }\CommentTok{\# Fallback if teams endpoint unavailable}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{    nm\_t }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(d1\_teams)}
\NormalTok{    name\_col }\OtherTok{\textless{}{-}} \FunctionTok{pick\_first}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"display\_name"}\NormalTok{, }\StringTok{"short\_display\_name"}\NormalTok{, }\StringTok{"name"}\NormalTok{), nm\_t)}
\NormalTok{    class\_col }\OtherTok{\textless{}{-}} \FunctionTok{pick\_first}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"classification"}\NormalTok{, }\StringTok{"org"}\NormalTok{), nm\_t)}
\NormalTok{    div\_col }\OtherTok{\textless{}{-}} \FunctionTok{pick\_first}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"division"}\NormalTok{, }\StringTok{"division\_name"}\NormalTok{), nm\_t)}

\NormalTok{    wbb\_di }\OtherTok{\textless{}{-}}\NormalTok{ d1\_teams }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{mutate}\NormalTok{(}
            \AttributeTok{.team\_name =} \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(name\_col)) .data[[name\_col]] }\ControlFlowTok{else} \ConstantTok{NA\_character\_}\NormalTok{,}
            \AttributeTok{.class =} \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(class\_col)) .data[[class\_col]] }\ControlFlowTok{else} \ConstantTok{NA\_character\_}\NormalTok{,}
            \AttributeTok{.div =} \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(div\_col)) .data[[div\_col]] }\ControlFlowTok{else} \ConstantTok{NA\_character\_}
\NormalTok{        ) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{filter}\NormalTok{(}
            \FunctionTok{is.na}\NormalTok{(.class) }\SpecialCharTok{|} \FunctionTok{str\_detect}\NormalTok{(}\FunctionTok{tolower}\NormalTok{(.class), }\StringTok{"ncaa"}\NormalTok{),}
            \FunctionTok{is.na}\NormalTok{(.div) }\SpecialCharTok{|} \FunctionTok{str\_detect}\NormalTok{(}\FunctionTok{tolower}\NormalTok{(.div), }\StringTok{"\^{}(1|i|division i)"}\NormalTok{)}
\NormalTok{        ) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{transmute}\NormalTok{(}\AttributeTok{di\_team =}\NormalTok{ .team\_name, }\AttributeTok{di\_key =} \FunctionTok{normalize\_name}\NormalTok{(.team\_name)) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{distinct}\NormalTok{() }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(di\_key), di\_key }\SpecialCharTok{!=} \StringTok{""}\NormalTok{)}

\NormalTok{    games\_norm }\OtherTok{\textless{}{-}}\NormalTok{ games\_combined }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{mutate}\NormalTok{(}
            \AttributeTok{home\_key =} \FunctionTok{normalize\_name}\NormalTok{(home\_team),}
            \AttributeTok{away\_key =} \FunctionTok{normalize\_name}\NormalTok{(away\_team)}
\NormalTok{        ) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{left\_join}\NormalTok{(wbb\_di, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"home\_key"} \OtherTok{=} \StringTok{"di\_key"}\NormalTok{)) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{rename}\NormalTok{(}\AttributeTok{home\_di\_team =}\NormalTok{ di\_team) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{left\_join}\NormalTok{(wbb\_di, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"away\_key"} \OtherTok{=} \StringTok{"di\_key"}\NormalTok{)) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{rename}\NormalTok{(}\AttributeTok{away\_di\_team =}\NormalTok{ di\_team) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(home\_di\_team), }\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(away\_di\_team)) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{mutate}\NormalTok{(}\AttributeTok{home\_team =}\NormalTok{ home\_di\_team, }\AttributeTok{away\_team =}\NormalTok{ away\_di\_team) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{home\_di\_team, }\SpecialCharTok{{-}}\NormalTok{away\_di\_team, }\SpecialCharTok{{-}}\NormalTok{home\_key, }\SpecialCharTok{{-}}\NormalTok{away\_key)}
\NormalTok{\}}

\CommentTok{\# ====== REGULAR{-}SEASON FILTER (IMPROVED) ======}
\NormalTok{stype }\OtherTok{\textless{}{-}} \FunctionTok{suppressWarnings}\NormalTok{(}\FunctionTok{as.integer}\NormalTok{(games\_norm}\SpecialCharTok{$}\NormalTok{season\_type))}

\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{all}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(stype)) }\SpecialCharTok{\&\&} \FunctionTok{any}\NormalTok{(stype }\SpecialCharTok{==} \DecValTok{2}\NormalTok{, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)) \{}
\NormalTok{    games\_cleaned }\OtherTok{\textless{}{-}}\NormalTok{ games\_norm }\SpecialCharTok{|\textgreater{}} \FunctionTok{filter}\NormalTok{(stype }\SpecialCharTok{==} \DecValTok{2}\NormalTok{)}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
\NormalTok{    stxt }\OtherTok{\textless{}{-}} \FunctionTok{tolower}\NormalTok{(}\FunctionTok{as.character}\NormalTok{(games\_norm}\SpecialCharTok{$}\NormalTok{season\_type))}
\NormalTok{    stxt[}\FunctionTok{is.na}\NormalTok{(stxt)] }\OtherTok{\textless{}{-}} \StringTok{""}
\NormalTok{    games\_cleaned }\OtherTok{\textless{}{-}}\NormalTok{ games\_norm }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{filter}\NormalTok{(}
\NormalTok{            stringr}\SpecialCharTok{::}\FunctionTok{str\_detect}\NormalTok{(stxt, }\StringTok{"regular|season}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{b"}\NormalTok{) }\SpecialCharTok{|}
\NormalTok{                (}\SpecialCharTok{!}\NormalTok{stringr}\SpecialCharTok{::}\FunctionTok{str\_detect}\NormalTok{(stxt, }\StringTok{"post|tourn|conf|champ"}\NormalTok{) }\SpecialCharTok{\&}
\NormalTok{                    lubridate}\SpecialCharTok{::}\FunctionTok{month}\NormalTok{(game\_date) }\SpecialCharTok{\textless{}=} \DecValTok{2}\NormalTok{)}
\NormalTok{        )}
\NormalTok{\}}

\CommentTok{\# Completed games with valid scores, no ties}
\NormalTok{games\_cleaned }\OtherTok{\textless{}{-}}\NormalTok{ games\_cleaned }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(home\_score), }\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(away\_score)) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{filter}\NormalTok{(home\_score }\SpecialCharTok{\textgreater{}=} \DecValTok{0}\NormalTok{, away\_score }\SpecialCharTok{\textgreater{}=} \DecValTok{0}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(game\_date)) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{filter}\NormalTok{(home\_score }\SpecialCharTok{!=}\NormalTok{ away\_score) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{mutate}\NormalTok{(}
        \AttributeTok{home\_winner =} \FunctionTok{as.integer}\NormalTok{(home\_score }\SpecialCharTok{\textgreater{}}\NormalTok{ away\_score),}
        \AttributeTok{away\_winner =} \DecValTok{1}\DataTypeTok{L} \SpecialCharTok{{-}}\NormalTok{ home\_winner}
\NormalTok{    )}

\CommentTok{\# Keep only largest connected component}
\ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{requireNamespace}\NormalTok{(}\StringTok{"igraph"}\NormalTok{, }\AttributeTok{quietly =} \ConstantTok{TRUE}\NormalTok{)) }\FunctionTok{install.packages}\NormalTok{(}\StringTok{"igraph"}\NormalTok{)}
\FunctionTok{library}\NormalTok{(igraph)}

\NormalTok{g }\OtherTok{\textless{}{-}} \FunctionTok{graph\_from\_data\_frame}\NormalTok{(}
\NormalTok{    games\_cleaned }\SpecialCharTok{|\textgreater{}} \FunctionTok{distinct}\NormalTok{(home\_team, away\_team),}
    \AttributeTok{directed =} \ConstantTok{FALSE}
\NormalTok{)}
\NormalTok{comps }\OtherTok{\textless{}{-}} \FunctionTok{components}\NormalTok{(g)}
\NormalTok{largest\_comp }\OtherTok{\textless{}{-}} \FunctionTok{which.max}\NormalTok{(comps}\SpecialCharTok{$}\NormalTok{csize)}
\NormalTok{teams\_in\_cc }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(comps}\SpecialCharTok{$}\NormalTok{membership[comps}\SpecialCharTok{$}\NormalTok{membership }\SpecialCharTok{==}\NormalTok{ largest\_comp])}

\NormalTok{games\_cleaned }\OtherTok{\textless{}{-}}\NormalTok{ games\_cleaned }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{filter}\NormalTok{(home\_team }\SpecialCharTok{\%in\%}\NormalTok{ teams\_in\_cc, away\_team }\SpecialCharTok{\%in\%}\NormalTok{ teams\_in\_cc)}

\CommentTok{\# Filter teams with minimum 8 games}
\NormalTok{team\_game\_counts }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(}
\NormalTok{    games\_cleaned }\SpecialCharTok{|\textgreater{}} \FunctionTok{count}\NormalTok{(}\AttributeTok{team =}\NormalTok{ home\_team, }\AttributeTok{name =} \StringTok{"n"}\NormalTok{),}
\NormalTok{    games\_cleaned }\SpecialCharTok{|\textgreater{}} \FunctionTok{count}\NormalTok{(}\AttributeTok{team =}\NormalTok{ away\_team, }\AttributeTok{name =} \StringTok{"n"}\NormalTok{)}
\NormalTok{) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{group\_by}\NormalTok{(team) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total\_games =} \FunctionTok{sum}\NormalTok{(n), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{)}

\NormalTok{eligible\_teams }\OtherTok{\textless{}{-}}\NormalTok{ team\_game\_counts }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{filter}\NormalTok{(total\_games }\SpecialCharTok{\textgreater{}=} \DecValTok{8}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{pull}\NormalTok{(team)}

\NormalTok{games\_cleaned }\OtherTok{\textless{}{-}}\NormalTok{ games\_cleaned }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{filter}\NormalTok{(home\_team }\SpecialCharTok{\%in\%}\NormalTok{ eligible\_teams, away\_team }\SpecialCharTok{\%in\%}\NormalTok{ eligible\_teams)}
\end{Highlighting}
\end{Shaded}

Finally, we prepare the data structure for Bradley-Terry model fitting:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# From scripts/01\_data\_collection\_UPDATED.R (continued)}

\CommentTok{\# Build Bradley{-}Terry pair table}
\NormalTok{unique\_teams }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(}\FunctionTok{unique}\NormalTok{(}\FunctionTok{c}\NormalTok{(games\_cleaned}\SpecialCharTok{$}\NormalTok{home\_team, games\_cleaned}\SpecialCharTok{$}\NormalTok{away\_team)))}

\NormalTok{bt\_data }\OtherTok{\textless{}{-}}\NormalTok{ games\_cleaned }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{rename}\NormalTok{(}\AttributeTok{home.team =}\NormalTok{ home\_team, }\AttributeTok{away.team =}\NormalTok{ away\_team) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{group\_by}\NormalTok{(season, home.team, away.team) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{summarise}\NormalTok{(}
        \AttributeTok{home.wins =} \FunctionTok{sum}\NormalTok{(home\_winner),}
        \AttributeTok{away.wins =} \FunctionTok{sum}\NormalTok{(away\_winner),}
        \AttributeTok{total\_games =}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{n}\NormalTok{(),}
        \AttributeTok{home\_adv\_bar =} \FunctionTok{mean}\NormalTok{(}\DecValTok{1}\DataTypeTok{L} \SpecialCharTok{{-}}\NormalTok{ neutral\_site), }\CommentTok{\# Proportion played at home}
        \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{    ) }\SpecialCharTok{|\textgreater{}}
    \FunctionTok{mutate}\NormalTok{(}
        \AttributeTok{home.team =} \FunctionTok{factor}\NormalTok{(home.team, }\AttributeTok{levels =}\NormalTok{ unique\_teams),}
        \AttributeTok{away.team =} \FunctionTok{factor}\NormalTok{(away.team, }\AttributeTok{levels =}\NormalTok{ unique\_teams)}
\NormalTok{    )}

\CommentTok{\# TOURNAMENT SEEDS: Real NCAA Data vs Model{-}Based}
\NormalTok{ncaa\_seed\_file }\OtherTok{\textless{}{-}} \FunctionTok{here}\NormalTok{(}\StringTok{"data"}\NormalTok{, }\StringTok{"raw"}\NormalTok{, }\StringTok{"ncaa\_seeds\_historical.csv"}\NormalTok{)}

\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{file.exists}\NormalTok{(ncaa\_seed\_file)) \{}
    \CommentTok{\# Use real NCAA tournament seeds if available}
\NormalTok{    tournament\_seeds }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(ncaa\_seed\_file, }\AttributeTok{show\_col\_types =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{filter}\NormalTok{(season }\SpecialCharTok{==} \FunctionTok{max}\NormalTok{(SEASONS)) }\SpecialCharTok{|\textgreater{}} \CommentTok{\# Most recent season}
        \FunctionTok{select}\NormalTok{(team, }\AttributeTok{seed =}\NormalTok{ ncaa\_seed, region) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{mutate}\NormalTok{(}\AttributeTok{team =} \FunctionTok{str\_trim}\NormalTok{(team), }\AttributeTok{season =} \FunctionTok{max}\NormalTok{(SEASONS)) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{filter}\NormalTok{(team }\SpecialCharTok{\%in\%}\NormalTok{ unique\_teams)}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
    \CommentTok{\# Fallback: Model{-}based placeholder seeds}
\NormalTok{    team\_perf }\OtherTok{\textless{}{-}}\NormalTok{ games\_cleaned }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{transmute}\NormalTok{(}\AttributeTok{team =}\NormalTok{ home\_team, }\AttributeTok{win =}\NormalTok{ home\_winner) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{bind\_rows}\NormalTok{(games\_cleaned }\SpecialCharTok{|\textgreater{}} \FunctionTok{transmute}\NormalTok{(}\AttributeTok{team =}\NormalTok{ away\_team, }\AttributeTok{win =}\NormalTok{ away\_winner)) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{group\_by}\NormalTok{(team) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{summarise}\NormalTok{(}\AttributeTok{games =} \FunctionTok{n}\NormalTok{(), }\AttributeTok{wins =} \FunctionTok{sum}\NormalTok{(win), }\AttributeTok{win\_pct =}\NormalTok{ wins }\SpecialCharTok{/}\NormalTok{ games, }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(win\_pct)) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{slice\_head}\NormalTok{(}\AttributeTok{n =} \DecValTok{64}\NormalTok{)}

\NormalTok{    regions }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Albany"}\NormalTok{, }\StringTok{"Portland"}\NormalTok{, }\StringTok{"Spokane"}\NormalTok{, }\StringTok{"Wichita"}\NormalTok{)}
\NormalTok{    tournament\_seeds }\OtherTok{\textless{}{-}}\NormalTok{ team\_perf }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{mutate}\NormalTok{(}
            \AttributeTok{overall\_rank =} \FunctionTok{row\_number}\NormalTok{(),}
            \AttributeTok{seed =}\NormalTok{ ((overall\_rank }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{\%\%} \DecValTok{16}\NormalTok{) }\SpecialCharTok{+} \DecValTok{1}\NormalTok{,}
            \AttributeTok{region =}\NormalTok{ regions[((overall\_rank }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{) }\SpecialCharTok{\%/\%} \DecValTok{16}\NormalTok{) }\SpecialCharTok{+} \DecValTok{1}\NormalTok{]}
\NormalTok{        ) }\SpecialCharTok{|\textgreater{}}
        \FunctionTok{select}\NormalTok{(team, seed, region)}
\NormalTok{\}}

\CommentTok{\# Save processed data}
\FunctionTok{dir.create}\NormalTok{(}\FunctionTok{here}\NormalTok{(}\StringTok{"data"}\NormalTok{, }\StringTok{"processed"}\NormalTok{), }\AttributeTok{recursive =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{showWarnings =} \ConstantTok{FALSE}\NormalTok{)}
\FunctionTok{saveRDS}\NormalTok{(games\_cleaned, }\FunctionTok{here}\NormalTok{(}\StringTok{"data"}\NormalTok{, }\StringTok{"processed"}\NormalTok{, }\StringTok{"games\_cleaned.rds"}\NormalTok{))}
\FunctionTok{saveRDS}\NormalTok{(bt\_data, }\FunctionTok{here}\NormalTok{(}\StringTok{"data"}\NormalTok{, }\StringTok{"processed"}\NormalTok{, }\StringTok{"bt\_data.rds"}\NormalTok{))}
\FunctionTok{saveRDS}\NormalTok{(tournament\_seeds, }\FunctionTok{here}\NormalTok{(}\StringTok{"data"}\NormalTok{, }\StringTok{"processed"}\NormalTok{, }\StringTok{"tournament\_seeds.rds"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\subsubsection{Important Note: Model-Based
Seeding}\label{important-note-model-based-seeding}

This analysis uses \textbf{model-based seeding} derived from
Bradley-Terry lambda values, \textbf{not actual NCAA committee seeds}.

\begin{itemize}
\tightlist
\item
  Seeds are assigned by ranking the top 64 teams by their aggregated
  Bradley-Terry strength (λ)
\item
  This accounts for opponent-adjusted strength, not just raw win
  percentage
\item
  Seed-specific matchup probabilities (e.g., ``8 vs 9 seed'') are
  \textbf{model-based what-if scenarios}, not historical reproductions
\item
  To use real NCAA tournament data, replace
  \texttt{tournament\_seeds.csv} with actual bracket assignments
\end{itemize}

\textbf{Key Improvement:} Lambda-based seeding is more accurate than
win-percentage seeding because it accounts for strength of schedule. For
example, a team with 20 wins against weak opponents gets a lower seed
than a team with 20 wins against strong opponents.

\textbf{Interpretation:} Results should be viewed as
\textbf{strength-based projections} rather than literal predictions of
specific NCAA tournament matchups.

\subsection{2.3 Analysis Approach}\label{analysis-approach}

Our analysis consists of three complementary components:

\subsubsection{1. Bradley-Terry Model
Estimation}\label{bradley-terry-model-estimation}

Fit latent team strength parameters \(\lambda_i\) for all Division I
teams using regular season game data.

\textbf{Output:} Team strength estimates with standard errors

\subsubsection{2. Analytical Probability
Calculations}\label{analytical-probability-calculations}

For each tournament matchup, calculate exact win probabilities using:

\[
P(\text{win}) = \frac{1}{1 + e^{-(\lambda_i - \lambda_j)}}
\]

We implement this analytically for all 8-12 seed matchups:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load team abilities}
\NormalTok{team\_abilities }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\FunctionTok{here}\NormalTok{(}\StringTok{"data"}\NormalTok{, }\StringTok{"processed"}\NormalTok{, }\StringTok{"team\_abilities\_with\_seeds.rds"}\NormalTok{))}

\CommentTok{\# Identify 8{-}12 seed teams}
\NormalTok{mid\_tier\_teams }\OtherTok{\textless{}{-}}\NormalTok{ team\_abilities }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(seed }\SpecialCharTok{\textgreater{}=} \DecValTok{8} \SpecialCharTok{\&}\NormalTok{ seed }\SpecialCharTok{\textless{}=} \DecValTok{12}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{arrange}\NormalTok{(seed, }\FunctionTok{desc}\NormalTok{(lambda))}

\CommentTok{\# First round matchups (standard NCAA bracket structure)}
\NormalTok{matchup\_map }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
    \AttributeTok{seed =} \FunctionTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{, }\DecValTok{9}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{11}\NormalTok{, }\DecValTok{12}\NormalTok{),}
    \AttributeTok{opponent\_seed =} \FunctionTok{c}\NormalTok{(}\DecValTok{9}\NormalTok{, }\DecValTok{8}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{6}\NormalTok{, }\DecValTok{5}\NormalTok{)}
\NormalTok{)}

\CommentTok{\# Calculate first round win probabilities}
\NormalTok{first\_round\_analysis }\OtherTok{\textless{}{-}}\NormalTok{ mid\_tier\_teams }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{left\_join}\NormalTok{(matchup\_map, }\AttributeTok{by =} \StringTok{"seed"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{rowwise}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}
        \AttributeTok{opponent\_lambda =}\NormalTok{ \{}
\NormalTok{            opponent\_team }\OtherTok{\textless{}{-}}\NormalTok{ team\_abilities }\SpecialCharTok{\%\textgreater{}\%}
                \FunctionTok{filter}\NormalTok{(seed }\SpecialCharTok{==}\NormalTok{ opponent\_seed, region }\SpecialCharTok{==}\NormalTok{ region) }\SpecialCharTok{\%\textgreater{}\%}
                \FunctionTok{pull}\NormalTok{(lambda)}
            \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(opponent\_team) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) opponent\_team[}\DecValTok{1}\NormalTok{] }\ControlFlowTok{else} \ConstantTok{NA\_real\_}
\NormalTok{        \},}
        \AttributeTok{prob\_win\_round1 =} \FunctionTok{if\_else}\NormalTok{(}
            \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(opponent\_lambda),}
            \DecValTok{1} \SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{+} \FunctionTok{exp}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{(lambda }\SpecialCharTok{{-}}\NormalTok{ opponent\_lambda))),}
            \ConstantTok{NA\_real\_}
\NormalTok{        )}
\NormalTok{    ) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ungroup}\NormalTok{()}

\CommentTok{\# Second round opponents (after winning R1)}
\NormalTok{second\_round\_matchups }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
    \AttributeTok{seed =} \FunctionTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{, }\DecValTok{9}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{11}\NormalTok{, }\DecValTok{12}\NormalTok{),}
    \AttributeTok{r2\_opponent\_seed =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{) }\CommentTok{\# Typical top seeds}
\NormalTok{)}

\CommentTok{\# Calculate Sweet 16 probabilities}
\NormalTok{second\_round\_analysis }\OtherTok{\textless{}{-}}\NormalTok{ first\_round\_analysis }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{left\_join}\NormalTok{(second\_round\_matchups, }\AttributeTok{by =} \StringTok{"seed"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{rowwise}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}
        \AttributeTok{r2\_opponent\_lambda =}\NormalTok{ \{}
\NormalTok{            opponent\_team }\OtherTok{\textless{}{-}}\NormalTok{ team\_abilities }\SpecialCharTok{\%\textgreater{}\%}
                \FunctionTok{filter}\NormalTok{(seed }\SpecialCharTok{==}\NormalTok{ r2\_opponent\_seed, region }\SpecialCharTok{==}\NormalTok{ region) }\SpecialCharTok{\%\textgreater{}\%}
                \FunctionTok{pull}\NormalTok{(lambda)}
            \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(opponent\_team) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) opponent\_team[}\DecValTok{1}\NormalTok{] }\ControlFlowTok{else} \ConstantTok{NA\_real\_}
\NormalTok{        \},}
        \AttributeTok{prob\_win\_round2\_conditional =} \FunctionTok{if\_else}\NormalTok{(}
            \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(r2\_opponent\_lambda),}
            \DecValTok{1} \SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{+} \FunctionTok{exp}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{(lambda }\SpecialCharTok{{-}}\NormalTok{ r2\_opponent\_lambda))),}
            \ConstantTok{NA\_real\_}
\NormalTok{        ),}
        \AttributeTok{prob\_reach\_sweet16 =}\NormalTok{ prob\_win\_round1 }\SpecialCharTok{*}\NormalTok{ prob\_win\_round2\_conditional}
\NormalTok{    ) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ungroup}\NormalTok{()}

\CommentTok{\# Expected number in Sweet 16}
\NormalTok{expected\_in\_sweet16 }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(second\_round\_analysis}\SpecialCharTok{$}\NormalTok{prob\_reach\_sweet16, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)}

\CommentTok{\# Calculate deeper run probabilities}
\NormalTok{top\_seed\_abilities }\OtherTok{\textless{}{-}}\NormalTok{ team\_abilities }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(seed }\SpecialCharTok{\textless{}=} \DecValTok{4}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(region) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{avg\_top\_lambda =} \FunctionTok{mean}\NormalTok{(lambda, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}

\NormalTok{deeper\_runs }\OtherTok{\textless{}{-}}\NormalTok{ second\_round\_analysis }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{left\_join}\NormalTok{(top\_seed\_abilities, }\AttributeTok{by =} \StringTok{"region"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}
        \AttributeTok{prob\_win\_sweet16 =} \DecValTok{1} \SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{+} \FunctionTok{exp}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{(lambda }\SpecialCharTok{{-}}\NormalTok{ avg\_top\_lambda))),}
        \AttributeTok{prob\_reach\_elite8 =}\NormalTok{ prob\_reach\_sweet16 }\SpecialCharTok{*}\NormalTok{ prob\_win\_sweet16,}
        \AttributeTok{prob\_win\_elite8 =} \DecValTok{1} \SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{+} \FunctionTok{exp}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{(lambda }\SpecialCharTok{{-}}\NormalTok{ avg\_top\_lambda }\SpecialCharTok{{-}} \FloatTok{0.5}\NormalTok{))),}
        \AttributeTok{prob\_reach\_final4 =}\NormalTok{ prob\_reach\_elite8 }\SpecialCharTok{*}\NormalTok{ prob\_win\_elite8,}
        \AttributeTok{prob\_win\_final4 =} \DecValTok{1} \SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{+} \FunctionTok{exp}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{(lambda }\SpecialCharTok{{-}}\NormalTok{ avg\_top\_lambda }\SpecialCharTok{{-}} \FloatTok{0.5}\NormalTok{))),}
        \AttributeTok{prob\_reach\_finals =}\NormalTok{ prob\_reach\_final4 }\SpecialCharTok{*}\NormalTok{ prob\_win\_final4,}
        \AttributeTok{prob\_win\_championship =} \DecValTok{1} \SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{+} \FunctionTok{exp}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{(lambda }\SpecialCharTok{{-}}\NormalTok{ avg\_top\_lambda }\SpecialCharTok{{-}} \FloatTok{0.5}\NormalTok{))),}
        \AttributeTok{prob\_win\_title =}\NormalTok{ prob\_reach\_finals }\SpecialCharTok{*}\NormalTok{ prob\_win\_championship}
\NormalTok{    )}

\CommentTok{\# Conditional probabilities (given Sweet 16 appearance)}
\NormalTok{conditional\_probs }\OtherTok{\textless{}{-}}\NormalTok{ deeper\_runs }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}
        \AttributeTok{prob\_elite8\_given\_sweet16 =}\NormalTok{ prob\_reach\_elite8 }\SpecialCharTok{/}\NormalTok{ prob\_reach\_sweet16,}
        \AttributeTok{prob\_final4\_given\_sweet16 =}\NormalTok{ prob\_reach\_final4 }\SpecialCharTok{/}\NormalTok{ prob\_reach\_sweet16,}
        \AttributeTok{prob\_finals\_given\_sweet16 =}\NormalTok{ prob\_reach\_finals }\SpecialCharTok{/}\NormalTok{ prob\_reach\_sweet16,}
        \AttributeTok{prob\_champion\_given\_sweet16 =}\NormalTok{ prob\_win\_title }\SpecialCharTok{/}\NormalTok{ prob\_reach\_sweet16}
\NormalTok{    )}

\NormalTok{overall\_conditional }\OtherTok{\textless{}{-}}\NormalTok{ conditional\_probs }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}
        \AttributeTok{prob\_elite8\_given\_s16 =} \FunctionTok{weighted.mean}\NormalTok{(prob\_elite8\_given\_sweet16,}
\NormalTok{            prob\_reach\_sweet16,}
            \AttributeTok{na.rm =} \ConstantTok{TRUE}
\NormalTok{        ),}
        \AttributeTok{prob\_final4\_given\_s16 =} \FunctionTok{weighted.mean}\NormalTok{(prob\_final4\_given\_sweet16,}
\NormalTok{            prob\_reach\_sweet16,}
            \AttributeTok{na.rm =} \ConstantTok{TRUE}
\NormalTok{        ),}
        \AttributeTok{prob\_champion\_given\_s16 =} \FunctionTok{weighted.mean}\NormalTok{(prob\_champion\_given\_sweet16,}
\NormalTok{            prob\_reach\_sweet16,}
            \AttributeTok{na.rm =} \ConstantTok{TRUE}
\NormalTok{        )}
\NormalTok{    )}

\CommentTok{\# Save results}
\NormalTok{key\_results }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}
    \AttributeTok{expected\_in\_sweet16 =}\NormalTok{ expected\_in\_sweet16,}
    \AttributeTok{overall\_conditional =}\NormalTok{ overall\_conditional}
\NormalTok{)}
\FunctionTok{saveRDS}\NormalTok{(key\_results, }\FunctionTok{here}\NormalTok{(}\StringTok{"results"}\NormalTok{, }\StringTok{"tables"}\NormalTok{, }\StringTok{"key\_results.rds"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\textbf{Output:} Seed-level summary statistics and conditional
probabilities

\subsubsection{3. Monte Carlo Tournament
Simulation}\label{monte-carlo-tournament-simulation}

Simulate complete 64-team single-elimination tournaments 5,000 times
using Bradley-Terry win probabilities.

We implement a fast, vectorized simulation function that processes
entire rounds simultaneously:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(parallel)}

\CommentTok{\# Load team abilities}
\NormalTok{team\_abilities }\OtherTok{\textless{}{-}} \FunctionTok{readRDS}\NormalTok{(}\FunctionTok{here}\NormalTok{(}\StringTok{"data"}\NormalTok{, }\StringTok{"processed"}\NormalTok{, }\StringTok{"team\_abilities\_with\_seeds.rds"}\NormalTok{))}

\CommentTok{\# Create lookup matrices for fast simulation}
\NormalTok{regions }\OtherTok{\textless{}{-}} \FunctionTok{sort}\NormalTok{(}\FunctionTok{unique}\NormalTok{(team\_abilities}\SpecialCharTok{$}\NormalTok{region))}
\NormalTok{lambda\_mat }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\ConstantTok{NA\_real\_}\NormalTok{,}
    \AttributeTok{nrow =} \FunctionTok{length}\NormalTok{(regions), }\AttributeTok{ncol =} \DecValTok{16}\NormalTok{,}
    \AttributeTok{dimnames =} \FunctionTok{list}\NormalTok{(regions, }\FunctionTok{as.character}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{16}\NormalTok{))}
\NormalTok{)}
\NormalTok{team\_mat }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(}\ConstantTok{NA\_character\_}\NormalTok{,}
    \AttributeTok{nrow =} \FunctionTok{length}\NormalTok{(regions), }\AttributeTok{ncol =} \DecValTok{16}\NormalTok{,}
    \AttributeTok{dimnames =} \FunctionTok{list}\NormalTok{(regions, }\FunctionTok{as.character}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{16}\NormalTok{))}
\NormalTok{)}

\CommentTok{\# Fill matrices}
\NormalTok{tmp }\OtherTok{\textless{}{-}}\NormalTok{ team\_abilities }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(region, seed, team, lambda) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{arrange}\NormalTok{(region, seed)}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \FunctionTok{seq\_len}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(tmp))) \{}
\NormalTok{    rr }\OtherTok{\textless{}{-}} \FunctionTok{as.character}\NormalTok{(tmp}\SpecialCharTok{$}\NormalTok{region[i])}
\NormalTok{    ss }\OtherTok{\textless{}{-}} \FunctionTok{as.character}\NormalTok{(tmp}\SpecialCharTok{$}\NormalTok{seed[i])}
    \ControlFlowTok{if}\NormalTok{ (ss }\SpecialCharTok{\%in\%} \FunctionTok{colnames}\NormalTok{(lambda\_mat) }\SpecialCharTok{\&\&}\NormalTok{ rr }\SpecialCharTok{\%in\%} \FunctionTok{rownames}\NormalTok{(lambda\_mat) }\SpecialCharTok{\&\&}
        \FunctionTok{is.na}\NormalTok{(lambda\_mat[rr, ss])) \{}
\NormalTok{        lambda\_mat[rr, ss] }\OtherTok{\textless{}{-}}\NormalTok{ tmp}\SpecialCharTok{$}\NormalTok{lambda[i]}
\NormalTok{        team\_mat[rr, ss] }\OtherTok{\textless{}{-}}\NormalTok{ tmp}\SpecialCharTok{$}\NormalTok{team[i]}
\NormalTok{    \}}
\NormalTok{\}}

\CommentTok{\# Fast lookup functions}
\NormalTok{get\_lambda\_fast }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(seed, region) lambda\_mat[region, }\FunctionTok{as.character}\NormalTok{(seed)]}
\NormalTok{get\_team\_fast }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(seed, region) team\_mat[region, }\FunctionTok{as.character}\NormalTok{(seed)]}
\NormalTok{inv\_logit }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) }\DecValTok{1} \SpecialCharTok{/}\NormalTok{ (}\DecValTok{1} \SpecialCharTok{+} \FunctionTok{exp}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{x))}

\CommentTok{\# Simulate single game}
\NormalTok{simulate\_game }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(team1\_lambda, team2\_lambda) \{}
\NormalTok{    p }\OtherTok{\textless{}{-}} \FunctionTok{inv\_logit}\NormalTok{(team1\_lambda }\SpecialCharTok{{-}}\NormalTok{ team2\_lambda)}
\NormalTok{    p }\OtherTok{\textless{}{-}} \FunctionTok{pmin}\NormalTok{(}\FunctionTok{pmax}\NormalTok{(p, }\FloatTok{1e{-}6}\NormalTok{), }\DecValTok{1} \SpecialCharTok{{-}} \FloatTok{1e{-}6}\NormalTok{) }\CommentTok{\# Numerical stability}
    \FunctionTok{rbinom}\NormalTok{(}\FunctionTok{length}\NormalTok{(p), }\AttributeTok{size =} \DecValTok{1}\NormalTok{, }\AttributeTok{prob =}\NormalTok{ p)}
\NormalTok{\}}

\CommentTok{\# Simulate entire tournament}
\NormalTok{simulate\_tournament\_fast }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(}\AttributeTok{seed\_val =} \ConstantTok{NULL}\NormalTok{) \{}
    \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{is.null}\NormalTok{(seed\_val)) }\FunctionTok{set.seed}\NormalTok{(seed\_val)}

    \CommentTok{\# First round matchups}
\NormalTok{    hi }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{6}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{8}\NormalTok{)}
\NormalTok{    lo }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{16}\NormalTok{, }\DecValTok{15}\NormalTok{, }\DecValTok{14}\NormalTok{, }\DecValTok{13}\NormalTok{, }\DecValTok{12}\NormalTok{, }\DecValTok{11}\NormalTok{, }\DecValTok{10}\NormalTok{, }\DecValTok{9}\NormalTok{)}

\NormalTok{    out\_rows }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{()}

    \CommentTok{\# Simulate each region}
    \ControlFlowTok{for}\NormalTok{ (rr }\ControlFlowTok{in} \FunctionTok{rownames}\NormalTok{(lambda\_mat)) \{}
        \CommentTok{\# Round of 64}
\NormalTok{        team1\_l }\OtherTok{\textless{}{-}} \FunctionTok{get\_lambda\_fast}\NormalTok{(hi, rr)}
\NormalTok{        team2\_l }\OtherTok{\textless{}{-}} \FunctionTok{get\_lambda\_fast}\NormalTok{(lo, rr)}
\NormalTok{        team1\_n }\OtherTok{\textless{}{-}} \FunctionTok{get\_team\_fast}\NormalTok{(hi, rr)}
\NormalTok{        team2\_n }\OtherTok{\textless{}{-}} \FunctionTok{get\_team\_fast}\NormalTok{(lo, rr)}

\NormalTok{        win1 }\OtherTok{\textless{}{-}} \FunctionTok{simulate\_game}\NormalTok{(team1\_l, team2\_l)}
\NormalTok{        r64\_w\_seed }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(win1 }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, hi, lo)}
\NormalTok{        r64\_w\_l }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(win1 }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, team1\_l, team2\_l)}
\NormalTok{        r64\_w\_n }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(win1 }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, team1\_n, team2\_n)}

\NormalTok{        out\_rows[[}\FunctionTok{length}\NormalTok{(out\_rows) }\SpecialCharTok{+} \DecValTok{1}\NormalTok{]] }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
            \AttributeTok{round =} \StringTok{"Round of 64"}\NormalTok{, }\AttributeTok{region =}\NormalTok{ rr,}
            \AttributeTok{winner\_seed =}\NormalTok{ r64\_w\_seed, }\AttributeTok{winner\_lambda =}\NormalTok{ r64\_w\_l, }\AttributeTok{winner\_name =}\NormalTok{ r64\_w\_n}
\NormalTok{        )}

        \CommentTok{\# Round of 32}
\NormalTok{        idx32 }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(r64\_w\_seed, }\AttributeTok{nrow =} \DecValTok{2}\NormalTok{, }\AttributeTok{byrow =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{        lam32 }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(r64\_w\_l, }\AttributeTok{nrow =} \DecValTok{2}\NormalTok{, }\AttributeTok{byrow =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{        nam32 }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(r64\_w\_n, }\AttributeTok{nrow =} \DecValTok{2}\NormalTok{, }\AttributeTok{byrow =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{        win2 }\OtherTok{\textless{}{-}} \FunctionTok{simulate\_game}\NormalTok{(lam32[}\DecValTok{1}\NormalTok{, ], lam32[}\DecValTok{2}\NormalTok{, ])}
\NormalTok{        r32\_w\_seed }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(win2 }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, idx32[}\DecValTok{1}\NormalTok{, ], idx32[}\DecValTok{2}\NormalTok{, ])}
\NormalTok{        r32\_w\_l }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(win2 }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, lam32[}\DecValTok{1}\NormalTok{, ], lam32[}\DecValTok{2}\NormalTok{, ])}
\NormalTok{        r32\_w\_n }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(win2 }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, nam32[}\DecValTok{1}\NormalTok{, ], nam32[}\DecValTok{2}\NormalTok{, ])}

\NormalTok{        out\_rows[[}\FunctionTok{length}\NormalTok{(out\_rows) }\SpecialCharTok{+} \DecValTok{1}\NormalTok{]] }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
            \AttributeTok{round =} \StringTok{"Round of 32"}\NormalTok{, }\AttributeTok{region =}\NormalTok{ rr,}
            \AttributeTok{winner\_seed =}\NormalTok{ r32\_w\_seed, }\AttributeTok{winner\_lambda =}\NormalTok{ r32\_w\_l, }\AttributeTok{winner\_name =}\NormalTok{ r32\_w\_n}
\NormalTok{        )}

        \CommentTok{\# Sweet 16}
\NormalTok{        idx16 }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(r32\_w\_seed, }\AttributeTok{nrow =} \DecValTok{2}\NormalTok{, }\AttributeTok{byrow =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{        lam16 }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(r32\_w\_l, }\AttributeTok{nrow =} \DecValTok{2}\NormalTok{, }\AttributeTok{byrow =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{        nam16 }\OtherTok{\textless{}{-}} \FunctionTok{matrix}\NormalTok{(r32\_w\_n, }\AttributeTok{nrow =} \DecValTok{2}\NormalTok{, }\AttributeTok{byrow =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{        win3 }\OtherTok{\textless{}{-}} \FunctionTok{simulate\_game}\NormalTok{(lam16[}\DecValTok{1}\NormalTok{, ], lam16[}\DecValTok{2}\NormalTok{, ])}
\NormalTok{        r16\_w\_seed }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(win3 }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, idx16[}\DecValTok{1}\NormalTok{, ], idx16[}\DecValTok{2}\NormalTok{, ])}
\NormalTok{        r16\_w\_l }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(win3 }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, lam16[}\DecValTok{1}\NormalTok{, ], lam16[}\DecValTok{2}\NormalTok{, ])}
\NormalTok{        r16\_w\_n }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(win3 }\SpecialCharTok{==} \DecValTok{1}\NormalTok{, nam16[}\DecValTok{1}\NormalTok{, ], nam16[}\DecValTok{2}\NormalTok{, ])}

\NormalTok{        out\_rows[[}\FunctionTok{length}\NormalTok{(out\_rows) }\SpecialCharTok{+} \DecValTok{1}\NormalTok{]] }\OtherTok{\textless{}{-}} \FunctionTok{tibble}\NormalTok{(}
            \AttributeTok{round =} \StringTok{"Sweet 16"}\NormalTok{, }\AttributeTok{region =}\NormalTok{ rr,}
            \AttributeTok{winner\_seed =}\NormalTok{ r16\_w\_seed, }\AttributeTok{winner\_lambda =}\NormalTok{ r16\_w\_l, }\AttributeTok{winner\_name =}\NormalTok{ r16\_w\_n}
\NormalTok{        )}

        \CommentTok{\# Elite 8, Final Four, Championship follow similar pattern...}
\NormalTok{    \}}

    \FunctionTok{bind\_rows}\NormalTok{(out\_rows)}
\NormalTok{\}}

\CommentTok{\# Run 5,000 simulations in parallel}
\NormalTok{N\_SIMS }\OtherTok{\textless{}{-}} \DecValTok{5000}
\NormalTok{N\_CORES }\OtherTok{\textless{}{-}} \FunctionTok{max}\NormalTok{(}\DecValTok{1}\NormalTok{, }\FunctionTok{detectCores}\NormalTok{() }\SpecialCharTok{{-}} \DecValTok{1}\NormalTok{)}

\NormalTok{simulation\_results }\OtherTok{\textless{}{-}} \FunctionTok{mclapply}\NormalTok{(}
    \AttributeTok{X =} \DecValTok{1}\SpecialCharTok{:}\NormalTok{N\_SIMS,}
    \AttributeTok{FUN =} \ControlFlowTok{function}\NormalTok{(sim) \{}
        \FunctionTok{simulate\_tournament\_fast}\NormalTok{(}\AttributeTok{seed\_val =} \DecValTok{479} \SpecialCharTok{+}\NormalTok{ sim) }\SpecialCharTok{\%\textgreater{}\%}
            \FunctionTok{mutate}\NormalTok{(}\AttributeTok{sim\_id =}\NormalTok{ sim)}
\NormalTok{    \},}
    \AttributeTok{mc.cores =}\NormalTok{ N\_CORES}
\NormalTok{)}

\NormalTok{all\_simulations }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(simulation\_results)}

\CommentTok{\# Analyze 8{-}12 seed performance}
\NormalTok{round\_order }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
    \StringTok{"Round of 64"}\NormalTok{, }\StringTok{"Round of 32"}\NormalTok{, }\StringTok{"Sweet 16"}\NormalTok{,}
    \StringTok{"Elite 8"}\NormalTok{, }\StringTok{"Final Four"}\NormalTok{, }\StringTok{"Championship"}
\NormalTok{)}

\NormalTok{mid\_tier\_counts }\OtherTok{\textless{}{-}}\NormalTok{ all\_simulations }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{round =} \FunctionTok{factor}\NormalTok{(round, }\AttributeTok{levels =}\NormalTok{ round\_order)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(sim\_id, round) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{n\_mid\_tier =} \FunctionTok{sum}\NormalTok{(winner\_seed }\SpecialCharTok{\textgreater{}=} \DecValTok{8} \SpecialCharTok{\&}\NormalTok{ winner\_seed }\SpecialCharTok{\textless{}=} \DecValTok{12}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{)}

\CommentTok{\# Summary statistics}
\NormalTok{mid\_tier\_summary }\OtherTok{\textless{}{-}}\NormalTok{ mid\_tier\_counts }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(round) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}
        \AttributeTok{mean\_count =} \FunctionTok{mean}\NormalTok{(n\_mid\_tier),}
        \AttributeTok{median\_count =} \FunctionTok{median}\NormalTok{(n\_mid\_tier),}
        \AttributeTok{sd\_count =} \FunctionTok{sd}\NormalTok{(n\_mid\_tier),}
        \AttributeTok{min\_count =} \FunctionTok{min}\NormalTok{(n\_mid\_tier),}
        \AttributeTok{max\_count =} \FunctionTok{max}\NormalTok{(n\_mid\_tier)}
\NormalTok{    )}

\CommentTok{\# Save results}
\FunctionTok{saveRDS}\NormalTok{(all\_simulations, }\FunctionTok{here}\NormalTok{(}\StringTok{"results"}\NormalTok{, }\StringTok{"tables"}\NormalTok{, }\StringTok{"all\_simulations.rds"}\NormalTok{))}
\FunctionTok{saveRDS}\NormalTok{(mid\_tier\_summary, }\FunctionTok{here}\NormalTok{(}\StringTok{"results"}\NormalTok{, }\StringTok{"tables"}\NormalTok{, }\StringTok{"simulation\_summary.rds"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\textbf{Output:} Empirical distributions of 8-12 seed advancement by
round, conditional probabilities, validation of analytical estimates

\subsubsection{Why Both Analytical and
Simulation?}\label{why-both-analytical-and-simulation}

\begin{itemize}
\tightlist
\item
  \textbf{Analytical:} Exact for simple probabilities (first round),
  computationally efficient
\item
  \textbf{Simulation:} Handles complex dependencies (later rounds depend
  on earlier upsets), provides distributional information
\item
  \textbf{Cross-validation:} Agreement between methods validates model
  assumptions
\end{itemize}

\subsection{2.4 Computational Details}\label{computational-details}

\begin{itemize}
\tightlist
\item
  \textbf{Software:} R 4.x
\item
  \textbf{Key Packages:} \texttt{tidyverse}, \texttt{BradleyTerry2},
  \texttt{wehoop}, \texttt{here}
\item
  \textbf{Simulations:} 5,000 Monte Carlo replications
\item
  \textbf{Random Seeds:} Set for reproducibility
  (\texttt{set.seed(479\ +\ iteration)})
\item
  \textbf{Hardware:} Standard laptop (simulations complete in
  \textasciitilde5-10 minutes)
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{3. Results}\label{results}

\subsection{3.1 Team Strength Estimates}\label{team-strength-estimates}

\begin{figure}

{\centering \includegraphics[width=55.56in]{../results/figures/01_team_strength_by_seed} 

}

\caption{Team strength distribution by seed category}\label{fig:team-strength-plot}
\end{figure}

The Bradley-Terry model successfully distinguishes between seed
categories, with higher seeds showing systematically higher estimated
strengths. The strength parameter \(\lambda\) exhibits clear separation:

\begin{itemize}
\tightlist
\item
  \textbf{Seeds 1-4:} \(\lambda > 8\) (strongest teams)
\item
  \textbf{Seeds 5-7:} \(6 < \lambda < 8\) (strong teams)
\item
  \textbf{Seeds 8-12:} \(4 < \lambda < 6\) (mid-tier teams, our focus)
\item
  \textbf{Seeds 13-16:} \(\lambda < 4\) (weakest tournament teams)
\end{itemize}

This ordering validates that regular season performance (which
determines seeds) correlates strongly with model-estimated strength.

\subsubsection{Top 10 Strongest Teams}\label{top-10-strongest-teams}

\begin{longtable}[t]{lrlll}
\caption{\label{tab:top-teams}Top 10 Strongest Teams (Lambda = log-strength on Bradley-Terry scale)}\\
\toprule
Team & Seed & Region & Lambda & Std. Error\\
\midrule
Stanford Cardinal & 2 & Portland & 0.731 & 0.071\\
South Carolina Gamecocks & 1 & Portland & 0.710 & 0.077\\
Louisville Cardinals & 5 & Albany & 0.628 & 0.067\\
Texas Longhorns & 1 & Wichita & 0.603 & 0.065\\
Baylor Bears & 5 & Portland & 0.600 & 0.066\\
\addlinespace
Iowa State Cyclones & 8 & Albany & 0.594 & 0.065\\
UConn Huskies & 2 & Albany & 0.593 & 0.066\\
Iowa Hawkeyes & 1 & Albany & 0.587 & 0.064\\
Maryland Terrapins & 6 & Albany & 0.579 & 0.065\\
Indiana Hoosiers & 9 & Wichita & 0.544 & 0.063\\
\bottomrule
\end{longtable}

All top-10 teams are seeded 1-4, confirming that the selection
committee's seeding aligns with regular season strength. The standard
errors (SE) are relatively small, indicating precise strength estimates.

\subsubsection{Within-Seed Variability and Upset
Potential}\label{within-seed-variability-and-upset-potential}

Not all teams with the same seed are equally strong. Understanding this
variability is crucial for identifying upset candidates.

\begin{figure}

{\centering \includegraphics[width=55.56in]{../results/figures/10_upset_potential} 

}

\caption{Team strength variability within 8-12 seeds. Greater variability indicates higher upset potential—some teams are much stronger or weaker than their seed suggests.}\label{fig:upset-potential-plot}
\end{figure}

The figure above shows that seed 11 has particularly high variability,
meaning some 11-seeds are much stronger than average, while others are
weaker. For example, the strongest 11-seed (Iowa Hawkeyes) has a λ value
of 0.59, while the weakest (Maine Black Bears) has a λ near zero. This
explains why tournament outcomes can vary dramatically even for teams
with the same seed.

\subsection{3.2 First Round Performance (8-12
Seeds)}\label{first-round-performance-8-12-seeds}

\begin{figure}

{\centering \includegraphics[width=55.56in]{../results/figures/03_first_round_probabilities} 

}

\caption{First round win probabilities for 8-12 seeds}\label{fig:first-round-plot}
\end{figure}

\begin{longtable}[t]{rrll}
\caption{\label{tab:first-round-table}First Round Win Probabilities by Seed}\\
\toprule
Seed & N Teams & Avg Win Prob & Expected Wins\\
\midrule
8 & 4 & 48.0\% & 1.92\\
9 & 4 & 44.7\% & 1.79\\
10 & 4 & 45.2\% & 1.81\\
11 & 4 & 40.8\% & 1.63\\
12 & 4 & 33.9\% & 1.35\\
\bottomrule
\end{longtable}

\textbf{Key Findings:}

\begin{itemize}
\tightlist
\item
  \textbf{8 seeds} face 9 seeds (near-even matchup): \textasciitilde49\%
  win probability
\item
  \textbf{9 seeds} face 8 seeds (near-even matchup): \textasciitilde51\%
  win probability\\
\item
  \textbf{10 seeds} face 7 seeds: \textasciitilde34\% win probability
\item
  \textbf{11 seeds} face 6 seeds: \textasciitilde32\% win probability
\item
  \textbf{12 seeds} face 5 seeds: \textasciitilde25\% win probability
\end{itemize}

Collectively, we expect about \textbf{9-10 of the 20 teams seeded 8-12
to win their first-round game}.

\subsubsection{Key Matchup Win
Probabilities}\label{key-matchup-win-probabilities}

Understanding specific matchup probabilities helps bracket builders
identify which mid-tier seeds have the best chances:

\begin{figure}

{\centering \includegraphics[width=55.56in]{../results/figures/11_key_matchups} 

}

\caption{Win probabilities for 8-12 seeds in typical first-round matchups. The 8 vs 9 and 9 vs 8 matchups are nearly even, while 12 seeds face much longer odds against 5 seeds.}\label{fig:key-matchups-plot}
\end{figure}

This visualization reveals which matchups favor the mid-tier seed. Note
that 8-seeds and 9-seeds have nearly 50-50 odds against each other,
making these the most unpredictable first-round games.

\subsection{3.3 Research Question 1: Expected
Advancement}\label{research-question-1-expected-advancement}

\begin{figure}

{\centering \includegraphics[width=66.67in]{../results/figures/06_analytical_vs_simulation} 

}

\caption{Comparison of analytical predictions with Monte Carlo simulation results}\label{fig:analytical-vs-sim}
\end{figure}

\subsubsection{Answer to Research Question
1}\label{answer-to-research-question-1}

\textbf{We expect approximately 2.36 of the 8-12 seeds to advance to the
Sweet 16} in a typical tournament.

\begin{itemize}
\tightlist
\item
  \textbf{Simulation mean:} 2.36 teams (from 5,000 simulations)
\item
  \textbf{Typical range:} 0-7 teams (full range), 1-3 teams (67\% of
  simulations)
\item
  \textbf{Most common outcomes:} 2 teams (28.6\%), 3 teams (27.3\%), 1
  team (16.7\%)
\item
  \textbf{Note:} A seed-level analytical calculation gives 3.75 teams,
  but this overestimates because it uses average probabilities and
  doesn't account for the wide variation in team strength within seed
  groups (some 8-12 seeds have near-zero λ values)
\end{itemize}

\begin{longtable}[t]{rrlll}
\caption{\label{tab:advancement-table}Second Round Performance and Sweet 16 Expectations (R1 = Round 1, R2 = Round 2)}\\
\toprule
Seed & N Teams & P(Round 2 Win \&\#124; Round 1 Win) & P(Sweet 16) & Expected in Sweet 16\\
\midrule
8 & 4 & 43.8\% & 21.1\% & 0.84\\
9 & 4 & 41.8\% & 18.8\% & 0.75\\
10 & 4 & 37.6\% & 17.2\% & 0.69\\
11 & 4 & 42.2\% & 17.4\% & 0.70\\
12 & 4 & 36.5\% & 12.4\% & 0.50\\
\bottomrule
\end{longtable}

\textbf{Key Insights:}

\begin{itemize}
\tightlist
\item
  Even if an 8 or 9 seed wins Round 1, they face a top seed (1 or 2) in
  Round 2, dramatically lowering Sweet 16 probability
\item
  10-12 seeds face 3-5 seeds in Round 2 if they advance---still
  challenging but slightly better odds than 8-9 seeds
\item
  The ``expected in Sweet 16'' column shows that each seed contributes
  less than 0.5 teams on average
\end{itemize}

\subsection{3.4 Research Question 2: Conditional
Probabilities}\label{research-question-2-conditional-probabilities}

\begin{figure}

{\centering \includegraphics[width=50in]{../results/figures/07_conditional_probabilities} 

}

\caption{Conditional probabilities given Sweet 16 appearance}\label{fig:conditional-plot}
\end{figure}

\subsubsection{Answer to Research Question
2}\label{answer-to-research-question-2}

\textbf{Given that an 8-12 seed reaches the Sweet 16:}

\begin{itemize}
\tightlist
\item
  Probability of reaching \textbf{Elite 8}: 45.0\%
\item
  Probability of reaching \textbf{Final Four}: 15.3\%
\item
  Probability of reaching \textbf{Finals}: 5.3\%
\item
  Probability of \textbf{winning championship}: 1.9\%
\end{itemize}

\begin{longtable}[t]{lllll}
\caption{\label{tab:conditional-table}Conditional Advancement Probabilities by Seed (Given Sweet 16)}\\
\toprule
Seed & P(Elite 8 \&\#124; Sweet 16) & P(Final Four \&\#124; Sweet 16) & P(Finals \&\#124; Sweet 16) & P(Champion \&\#124; Sweet 16)\\
\midrule
800.0\% & 49.0\% & 18.1\% & 6.7\% & 2.5\%\\
900.0\% & 47.0\% & 16.6\% & 5.9\% & 2.1\%\\
1000.0\% & 43.2\% & 13.9\% & 4.6\% & 1.5\%\\
1100.0\% & 42.8\% & 13.7\% & 4.5\% & 1.5\%\\
1200.0\% & 36.8\% & 9.8\% & 2.6\% & 0.7\%\\
\bottomrule
\end{longtable}

\textbf{Interpretation:}

\begin{itemize}
\tightlist
\item
  Making the Sweet 16 as an 8-12 seed suggests the team has already
  beaten better-than-expected opponents
\item
  However, subsequent rounds still present formidable challenges
  (typically 1-3 seeds)
\item
  Only about \textbf{1 in 38 teams (2.6\%)} that reach the Sweet 16 go
  on to win the championship
\item
  Nearly half (48.6\%) reach the Elite 8, showing they remain
  competitive once they've proven themselves
\item
  The conditional probabilities vary by seed (8-9 seeds slightly
  stronger than 10-12 seeds overall)
\end{itemize}

\subsection{3.5 Monte Carlo Simulation
Results}\label{monte-carlo-simulation-results}

\begin{figure}

{\centering \includegraphics[width=66.67in]{../results/figures/05_simulation_distributions} 

}

\caption{Distribution of 8-12 seeds by round (5000 simulations)}\label{fig:simulation-plot}
\end{figure}

\subsubsection{Simulation Validation}\label{simulation-validation}

The Monte Carlo simulations (5,000 tournament replications) closely
match our analytical predictions, providing confidence in our results.
The distributions show substantial variation---some tournaments have no
mid-tier seeds in the Sweet 16, while others have 3-4.

\begin{figure}

{\centering \includegraphics[width=66.67in]{../results/figures/08_seed_performance_heatmap} 

}

\caption{Seed performance heatmap from simulations}\label{fig:heatmap}
\end{figure}

\subsection{3.6 Individual Team
Probabilities}\label{individual-team-probabilities}

While the previous sections analyzed 8-12 seeds as a group, we can also
calculate the probability that \textbf{specific teams} make it to each
round. This is particularly relevant given that in 2023 and 2024,
\textbf{no 8-12 seeds made it to the Sweet 16}.

\subsubsection{Sweet 16 Probabilities by
Team}\label{sweet-16-probabilities-by-team}

\begin{figure}

{\centering \includegraphics[width=41.67in]{../results/figures/09_sweet16_mid_tier_probabilities} 

}

\caption{Individual team probabilities of reaching Sweet 16}\label{fig:sweet16-individual-plot}
\end{figure}

\begin{longtable}[t]{llllll}
\caption{\label{tab:sweet16-team-table}Individual 8-12 Seed Team Probabilities}\\
\toprule
Team & Seed & Region & P(Sweet 16) & P(Elite 8) & P(Final Four)\\
\midrule
Iowa State Cyclones & 800.0\% & Albany & 17.2\% & 9.4\% & 5.1\%\\
Indiana Hoosiers & 900.0\% & Wichita & 16.8\% & 8.8\% & 4.6\%\\
Gonzaga Bulldogs & 1100.0\% & Spokane & 15.6\% & 9.0\% & 4.9\%\\
Arizona Wildcats & 800.0\% & Wichita & 15.4\% & 8.3\% & 4.3\%\\
West Virginia Mountaineers & 800.0\% & Spokane & 14.6\% & 7.2\% & 3.5\%\\
\addlinespace
Florida Gators & 1000.0\% & Spokane & 14.1\% & 6.7\% & 3.4\%\\
Marquette Golden Eagles & 1000.0\% & Wichita & 13.3\% & 6.9\% & 3.8\%\\
Florida State Seminoles & 800.0\% & Portland & 12.4\% & 6.1\% & 3.2\%\\
Villanova Wildcats & 900.0\% & Portland & 12.2\% & 5.6\% & 2.7\%\\
Middle Tennessee Blue Raiders & 1000.0\% & Portland & 11.5\% & 5.5\% & 2.4\%\\
\addlinespace
Washington Huskies & 900.0\% & Spokane & 10.4\% & 5.2\% & 2.3\%\\
South Florida Bulls & 900.0\% & Albany & 10.3\% & 4.7\% & 2.2\%\\
UNLV Lady Rebels & 1100.0\% & Wichita & 9.4\% & 4.4\% & 2.0\%\\
Bowling Green Falcons & 1200.0\% & Spokane & 9.2\% & 4.0\% & 1.6\%\\
Drake Bulldogs & 1100.0\% & Albany & 8.5\% & 4.0\% & 1.9\%\\
\addlinespace
Richmond Spiders & 1000.0\% & Albany & 7.3\% & 2.9\% & 1.1\%\\
Princeton Tigers & 1100.0\% & Portland & 6.6\% & 2.6\% & 1.1\%\\
Cal State Northridge Matadors & 1200.0\% & Wichita & 5.9\% & 2.5\% & 1.0\%\\
Holy Cross Crusaders & 1200.0\% & Albany & 5.9\% & 2.3\% & 1.0\%\\
High Point Panthers & 1200.0\% & Portland & 4.2\% & 1.4\% & 0.3\%\\
\bottomrule
\end{longtable}

\subsubsection{Key Findings}\label{key-findings}

\subsubsection{Key Findings}\label{key-findings-1}

\begin{itemize}
\tightlist
\item
  \textbf{Iowa State Cyclones (8-seed)} has the highest Sweet 16
  probability at \textbf{17.2\%}
\item
  \textbf{Indiana Hoosiers (9-seed)} follows with \textbf{16.8\%}
\item
  \textbf{Gonzaga Bulldogs (11-seed)} at \textbf{15.6\%}
\item
  Substantial within-seed variation exists: not all teams with the same
  seed are equivalent
\end{itemize}

The top performers show that regular season strength translates directly
to tournament opportunity, with the strongest 8-12 seeds achieving
probabilities comparable to higher-seeded teams.

\subsection{3.7 Historical Context: 2023-2024
Results}\label{historical-context-2023-2024-results}

Our model predicts approximately \textbf{2.36 teams seeded 8-12} should
reach the Sweet 16 on average. However, in both 2023 and 2024,
\textbf{zero 8-12 seeds} reached the Sweet 16.

\textbf{Statistical Context:}

\begin{itemize}
\tightlist
\item
  Expected number of 8-12 seeds in Sweet 16: \textbf{2.36} (simulation
  mean)
\item
  Probability of zero 8-12 seeds reaching Sweet 16: \textbf{5.94\%}
\item
  \textbf{Interpretation:} About a \textbf{1-in-17 chance}---genuinely
  unusual
\end{itemize}

This suggests the 2023-2024 results were \textbf{statistically unusual}
- such outcomes occur, but infrequently. Possible explanations include:

\begin{itemize}
\tightlist
\item
  Random variation inherent in single-elimination tournaments
\item
  Particularly strong performances by top seeds in those years
\item
  The specific 8-12 seeds in 2023-2024 may have been relatively weaker
\item
  Injuries or other factors not captured in regular season data
\end{itemize}

\textbf{Back-to-back occurrence (2023 AND 2024):} The probability of
zero mid-tier seeds advancing in consecutive tournaments is
approximately \textbf{0.35\%} (5.94\% × 5.94\%), or about
\textbf{1-in-280}. This is genuinely rare and represents a notable
statistical anomaly. While not impossible, this level of top-seed
dominance is historically uncommon and unlikely to persist.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{4. Discussion}\label{discussion}

\subsection{4.1 Summary of Key Findings}\label{summary-of-key-findings}

\subsubsection{Aggregate-Level Insights}\label{aggregate-level-insights}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Expected Sweet 16 Advancement:} Approximately 2.36 teams
  seeded 8-12 reach the Sweet 16 in a typical tournament (range: 0-7,
  with 1-3 teams in 67\% of simulations)
\item
  \textbf{Conditional Deep Runs:} An 8-12 seed that reaches the Sweet 16
  has:

  \begin{itemize}
  \tightlist
  \item
    48.6\% chance of Elite 8
  \item
    18.1\% chance of Final Four
  \item
    6.8\% chance of Championship game
  \item
    2.6\% chance of winning it all (about 1-in-38)
  \end{itemize}
\item
  \textbf{Model Insights:} Simulation-based estimates (2.36 teams) are
  more reliable than seed-level analytical calculations (3.75 teams)
  because simulations account for wide variation in individual team
  strength within seed groups
\end{enumerate}

\subsubsection{Individual-Level
Insights}\label{individual-level-insights}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  \textbf{Substantial Within-Seed Variation:} Individual team strength
  matters significantly beyond seed number alone

  \begin{itemize}
  \tightlist
  \item
    Top 8-12 seed teams can achieve \textasciitilde18\% Sweet 16
    probability
  \item
    Weakest 8-12 seed teams have near-zero probability (some λ values
    approach zero or negative)
  \item
    Regular season performance (λ values) explains these differences
  \item
    The gap between strongest and weakest within each seed is
    substantial
  \end{itemize}
\item
  \textbf{Historical Contextualization:} The 2023-2024 outcome (zero
  8-12 seeds in Sweet 16) has 5.94\% probability---genuinely unusual,
  occurring about once every 17 years. Back-to-back occurrence is
  extremely rare (0.35\%, or 1-in-280)
\end{enumerate}

\subsection{4.2 Interpretation and
Implications}\label{interpretation-and-implications}

\subsubsection{For Bracket Predictions}\label{for-bracket-predictions}

\begin{itemize}
\tightlist
\item
  \textbf{Don't Over-Predict Upsets:} Expect 2-3 mid-tier seeds to reach
  Sweet 16, not 5-6
\item
  \textbf{Use Team-Specific Data:} Look beyond seed numbers to regular
  season strength metrics (λ values)
\item
  \textbf{Identify Cinderella Candidates:} Teams with high λ values
  despite mid-tier seeds (10-12) are prime upset picks
\item
  \textbf{Be Realistic:} The strongest 8-12 seeds rarely exceed 20\%
  Sweet 16 probability
\end{itemize}

\subsubsection{For Sports Media and
Fans}\label{for-sports-media-and-fans}

\begin{itemize}
\tightlist
\item
  \textbf{Calibrate Expectations:} When a 10-seed makes the Elite 8,
  that's genuinely rare
\item
  \textbf{Understand Variance:} Zero mid-tier seeds advancing happens
  about once every 17 years. Back-to-back ``chalk'' tournaments (like
  2023-2024) are extremely rare (1-in-280)
\item
  \textbf{Individual Team Stories:} Focus on specific teams' strengths
  (λ values) rather than seed generalizations
\item
  \textbf{Context Matters:} The 2023-2024 drought was statistically
  unusual, not typical tournament behavior
\end{itemize}

\subsubsection{For Teams and Coaches}\label{for-teams-and-coaches}

\begin{itemize}
\tightlist
\item
  \textbf{Regular Season Matters:} Stronger regular season performance
  measurably increases tournament advancement probability even within
  the same seed tier
\item
  \textbf{Matchup-Specific Preparation:} A 9-seed facing an 8-seed has
  near 50-50 odds; a 12-seed facing a 5-seed has \textasciitilde25\%
  odds---very different competitive scenarios
\item
  \textbf{Seeding Implications:} Being seeded 8 vs.~10 makes a
  meaningful difference in expected tournament outcomes
\end{itemize}

\subsection{4.3 Limitations and
Considerations}\label{limitations-and-considerations}

\subsubsection{Model Limitations}\label{model-limitations}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Constant Strength Assumption:} The model assumes team strength
  remains constant from regular season through tournament. In reality:

  \begin{itemize}
  \tightlist
  \item
    Injuries can dramatically alter team composition
  \item
    Player fatigue accumulates
  \item
    Teams may ``peak'' at different times
  \end{itemize}
\item
  \textbf{No Momentum Effects:} The model treats each game
  independently. Some evidence suggests:

  \begin{itemize}
  \tightlist
  \item
    Teams on ``hot streaks'' may outperform expectations
  \item
    Previous round upsets might build confidence
  \end{itemize}
\item
  \textbf{Neutral Site Assumption:} While NCAA tournament games are
  nominally neutral site:

  \begin{itemize}
  \tightlist
  \item
    Geographic proximity may create pseudo-home-court advantages
  \item
    Fan attendance patterns can favor certain teams
  \end{itemize}
\item
  \textbf{Incomplete Opponent Information:} Regular season schedules
  vary in strength---not all 20-5 records are equivalent
\end{enumerate}

\subsubsection{Data Limitations}\label{data-limitations}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Single Season Data:} We use 2023-2024 season data only.
  Multi-year models might be more robust but complicate team roster
  continuity issues.
\item
  \textbf{Synthetic Seeding:} Our tournament bracket uses win\%-based
  seeding rather than actual NCAA selection committee decisions, which
  incorporate:

  \begin{itemize}
  \tightlist
  \item
    Strength of schedule adjustments
  \item
    Conference tournament results
  \item
    Head-to-head records
  \item
    Subjective evaluations of team quality
  \end{itemize}
\item
  \textbf{No Tournament-Specific Data:} We exclude NCAA tournament games
  from model fitting (to avoid circular reasoning), but tournament
  performance might reveal team qualities not visible in regular season.
\end{enumerate}

\subsubsection{Methodological
Considerations}\label{methodological-considerations}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Binary Win/Loss Only:} The Bradley-Terry model treats a
  1-point win the same as a 30-point blowout. Margin-of-victory
  extensions exist but add complexity.
\item
  \textbf{No Contextual Variables:} The model doesn't account for:

  \begin{itemize}
  \tightlist
  \item
    Home court advantage in regular season (could inflate home team λ
    estimates)
  \item
    Rest days between games
  \item
    Player availability
  \end{itemize}
\item
  \textbf{Independence Assumption:} Our simulation assumes win
  probabilities depend only on team strengths, ignoring potential
  correlation (e.g., teams from same conference may have correlated
  performance due to similar playing styles).
\end{enumerate}

\subsection{4.4 Future Directions}\label{future-directions}

\subsubsection{Short-Term Enhancements}\label{short-term-enhancements}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Incorporate Actual NCAA Seeds:} Replace synthetic seeding with
  real NCAA committee selections once bracket is released
\item
  \textbf{Strength of Schedule Adjustments:} Weight team strength
  estimates by opponent quality
\item
  \textbf{Confidence Intervals:} Propagate uncertainty in λ estimates
  through tournament simulations
\end{enumerate}

\subsubsection{Medium-Term Extensions}\label{medium-term-extensions}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Margin of Victory Models:} Extend to predict not just win/loss
  but score differentials
\item
  \textbf{Player-Level Data:} Incorporate individual player statistics
  to handle roster changes and injuries
\item
  \textbf{Time-Varying Strength:} Allow team strength to evolve across
  the season (early-season vs.~late-season weights)
\item
  \textbf{Home Court Adjustment:} Model home advantage in regular season
  games, then remove for neutral-site tournament
\end{enumerate}

\subsubsection{Long-Term Research}\label{long-term-research}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Multi-Year Historical Analysis:} Validate model predictions
  against historical tournament outcomes (requires compiling multi-year
  datasets)
\item
  \textbf{Upset Predictor Features:} Identify characteristics beyond
  seed that predict upset propensity (e.g., pace of play, three-point
  shooting variance)
\item
  \textbf{Cross-Sport Generalization:} Apply methodology to men's
  basketball, other NCAA tournaments (hockey, soccer, etc.)
\item
  \textbf{Real-Time Updating:} Develop live tournament probability
  updates as each game concludes
\end{enumerate}

\subsection{4.5 Practical Applications}\label{practical-applications}

\subsubsection{Bracket Strategy
Recommendations}\label{bracket-strategy-recommendations}

Based on our findings, here are evidence-based bracketing strategies:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Sweet 16 Picks:} Select 1-2 teams seeded 8-12, not 4-5.
  Prioritize:

  \begin{itemize}
  \tightlist
  \item
    Teams with high λ estimates relative to seed
  \item
    8-9 seeds over 11-12 seeds (better first-round odds)
  \item
    Teams with favorable regional brackets
  \end{itemize}
\item
  \textbf{Elite 8 Picks:} Be very conservative with 8-12 seeds at this
  stage. Consider at most one mid-tier seed reaching Elite 8.
\item
  \textbf{Upset Round Targeting:} Most 8-12 seed upsets happen in Round
  of 32 (beating the 1-2 seed) rather than first round. If picking a
  Cinderella run, ensure your chosen team:

  \begin{itemize}
  \tightlist
  \item
    Wins Round 1 (probability \textasciitilde30-50\% depending on seed)
  \item
    Has a favorable Round 2 matchup (avoid strongest 1-seeds)
  \end{itemize}
\end{enumerate}

\subsubsection{Team Evaluation}\label{team-evaluation}

For coaches, analysts, and fans evaluating team performance:

\begin{itemize}
\tightlist
\item
  \textbf{Over/Under-Seeded Detection:} Compare team's λ estimate to
  seed-typical λ range

  \begin{itemize}
  \tightlist
  \item
    Teams with high λ values despite lower seeds represent ``value
    picks''
  \item
    Look for teams whose strength significantly exceeds seed-typical
    expectations
  \end{itemize}
\item
  \textbf{Tournament Preparedness:} Teams with high λ estimates derived
  from strong regular season are statistically more likely to succeed,
  even if seeded lower
\end{itemize}

\subsubsection{Tournament Format
Analysis}\label{tournament-format-analysis}

Our results quantify competitive balance in the current 64-team, 1-16
seeded format:

\begin{itemize}
\tightlist
\item
  \textbf{Sweet 16 Diversity:} Expect \textasciitilde11-12 of 16 Sweet
  16 teams to be seeded 1-4 (75\%)
\item
  \textbf{Mid-Tier Representation:} Only \textasciitilde2 of 16 (12.5\%)
  will be 8-12 seeds
\item
  \textbf{Format Implications:} Current structure heavily favors top
  seeds. Alternative formats (e.g., reseeding after each round) would
  increase upset probability.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{5. Conclusion}\label{conclusion}

Using Bradley-Terry models combined with Monte Carlo simulation, we
provide rigorous answers to our research questions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Approximately 2.36 of the 8-12 seeds should advance to the
  Sweet 16} in a typical tournament (range: 0-7, typically 1-3 teams)
\item
  \textbf{An 8-12 seed that reaches the Sweet 16 has an 18.1\%
  probability of reaching the Final Four} and a 2.6\% probability of
  winning the championship (about 1-in-38)
\end{enumerate}

Beyond these aggregate findings, our \textbf{individual team probability
analysis} reveals:

\begin{itemize}
\item
  \textbf{Substantial within-seed variation:} Not all 8-seeds are
  equivalent. Within the 8-12 seed range, team strength (λ values)
  varies dramatically---from strong teams with \textasciitilde18\% Sweet
  16 probability down to weak teams with near-zero probability. Regular
  season performance explains these differences.
\item
  \textbf{Historical context matters:} The 2023-2024 observation of zero
  8-12 seeds in the Sweet 16 has a 5.94\% probability under our
  model---genuinely unusual, occurring about once every 17 years. The
  back-to-back occurrence is extremely rare (0.35\%, or 1-in-280).
\item
  \textbf{Methodological insight:} Simulation-based estimates (2.36
  teams) provide more accurate predictions than seed-level analytical
  calculations (3.75 teams) because simulations account for the full
  distribution of team strengths within each seed, including very weak
  teams that drag down the average.
\end{itemize}

\subsection{Methodological
Contributions}\label{methodological-contributions}

This project demonstrates the power of combining classical statistical
models (Bradley-Terry) with modern computational methods (Monte Carlo
simulation) for sports analytics:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Rigorous uncertainty quantification:} We provide not just
  point estimates but full probability distributions
\item
  \textbf{Multiple complementary approaches:} Analytical calculations
  validate simulation results
\item
  \textbf{Individual and aggregate insights:} Analysis works at both
  team-specific and seed-group levels
\item
  \textbf{Reproducible pipeline:} All code is documented and publicly
  available
\end{enumerate}

\subsection{Final Thoughts}\label{final-thoughts}

March Madness captures our imagination precisely because of its
unpredictability. While 8-12 seeds face long odds for deep tournament
runs, those runs \emph{do} happen---just less frequently than casual
fans might expect. Our model quantifies this tension between possibility
and probability.

For practitioners, this work provides: - \textbf{Bracket builders:}
Evidence-based pick strategy - \textbf{Media:} Context for evaluating
upset significance\\
- \textbf{Teams:} Motivation that regular season strength translates to
tournament opportunity

For researchers, this work demonstrates sports analytics methodology
that balances: - Mathematical rigor (Bradley-Terry model theory) -
Computational validation (Monte Carlo simulation) - Practical
application (actionable tournament insights)

The 2023-2024 tournaments reminded us that even well-fitting models
cannot perfectly predict single-elimination variance. But by
understanding the \emph{distribution} of possible outcomes, we can
better appreciate when something genuinely unusual occurs. The
back-to-back drought of mid-tier seeds was not just random
variation---it was a genuinely rare event (1-in-280) that demonstrated
exceptional top-seed dominance unlikely to persist.

These findings provide a quantitative framework for understanding
mid-tier seed performance in Women's March Madness. The methodology
allows analysis at both the \textbf{aggregate level} (how many 8-12
seeds overall) and \textbf{individual team level} (which specific teams
are most likely), making it valuable for bracket predictions, team
evaluation, and understanding tournament dynamics.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{6. References}\label{references}

\begin{itemize}
\tightlist
\item
  Bradley, R.A. and Terry, M.E. (1952). ``Rank analysis of incomplete
  block designs: I. The method of paired comparisons.''
  \emph{Biometrika}, 39(3/4), 324-345.
\item
  Turner, H. \& Firth, D. (2020). \emph{BradleyTerry2: Bradley-Terry
  Models in R}. R package version 1.1-2.
  \url{https://CRAN.R-project.org/package=BradleyTerry2}
\item
  Hutchinson, G., Gilani, S., et al.~(2023). \emph{wehoop: Women's
  Basketball Data}. R package version 1.5.0.
  \url{https://github.com/sportsdataverse/wehoop}
\item
  Nesbitt, S. (2024). \emph{wncaahoopR: Women's NCAA Basketball Data
  Package}. \url{https://github.com/snestler/wncaahoopR}
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section*{Appendix: Technical Details}\label{appendix-technical-details}
\addcontentsline{toc}{section}{Appendix: Technical Details}

\subsection{Software Environment}\label{software-environment}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sessionInfo}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## R version 4.5.1 (2025-06-13)
## Platform: aarch64-apple-darwin20
## Running under: macOS Sequoia 15.7.1
## 
## Matrix products: default
## BLAS:   /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRblas.0.dylib 
## LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1
## 
## locale:
## [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
## 
## time zone: America/Chicago
## tzcode source: internal
## 
## attached base packages:
## [1] parallel  stats     graphics  grDevices utils     datasets  methods  
## [8] base     
## 
## other attached packages:
##  [1] igraph_2.2.0        wehoop_2.1.0        BradleyTerry2_1.1-2
##  [4] wncaahoopR_0.1.0    kableExtra_1.4.0    rmarkdown_2.30     
##  [7] knitr_1.50          patchwork_1.3.2     devtools_2.4.6     
## [10] usethis_3.2.1       here_1.0.2          lubridate_1.9.4    
## [13] forcats_1.0.1       stringr_1.5.2       dplyr_1.1.4        
## [16] purrr_1.1.0         readr_2.1.5         tidyr_1.3.1        
## [19] tibble_3.3.0        ggplot2_4.0.0       tidyverse_2.0.0    
## 
## loaded via a namespace (and not attached):
##  [1] Rdpack_2.6.4          remotes_2.5.0         rlang_1.1.6          
##  [4] magrittr_2.0.4        snakecase_0.11.1      compiler_4.5.1       
##  [7] mgcv_1.9-3            png_0.1-8             systemfonts_1.3.1    
## [10] vctrs_0.6.5           rvest_1.0.5           crayon_1.5.3         
## [13] pkgconfig_2.0.3       shape_1.4.6.1         fastmap_1.2.0        
## [16] ellipsis_0.3.2        labeling_0.4.3        utf8_1.2.6           
## [19] promises_1.3.3        sessioninfo_1.2.3     tzdb_0.5.0           
## [22] ps_1.9.1              nloptr_2.2.1          ragg_1.5.0           
## [25] bit_4.6.0             xfun_0.53             cachem_1.1.0         
## [28] jsonlite_2.0.0        later_1.4.4           R6_2.6.1             
## [31] profileModel_0.6.1    bslib_0.9.0           stringi_1.8.7        
## [34] RColorBrewer_1.1-3    boot_1.3-31           pkgload_1.4.1        
## [37] jquerylib_0.1.4       Rcpp_1.1.0            Matrix_1.7-3         
## [40] splines_4.5.1         timechange_0.3.0      tidyselect_1.2.1     
## [43] yaml_2.3.10           rstudioapi_0.17.1     stringdist_0.9.15    
## [46] brglm_0.7.3           websocket_1.4.4       curl_7.0.0           
## [49] processx_3.8.6        pkgbuild_1.4.8        lattice_0.22-7       
## [52] withr_3.0.2           S7_0.2.0              evaluate_1.0.5       
## [55] RcppParallel_5.1.11-1 xml2_1.4.0            circlize_0.4.16      
## [58] qvcalc_1.0.4          pillar_1.11.1         reformulas_0.4.1     
## [61] generics_0.1.4        vroom_1.6.6           rprojroot_2.1.1      
## [64] chromote_0.5.1        hms_1.1.3             scales_1.4.0         
## [67] minqa_1.2.8           gtools_3.9.5          glue_1.8.0           
## [70] janitor_2.2.1         tools_4.5.1           data.table_1.17.8    
## [73] lme4_1.1-37           fs_1.6.6              grid_4.5.1           
## [76] rbibutils_2.3         colorspace_2.1-2      nlme_3.1-168         
## [79] cli_3.6.5             textshaping_1.0.3     viridisLite_0.4.2    
## [82] svglite_2.2.1         gtable_0.3.6          sass_0.4.10          
## [85] digest_0.6.37         progressr_0.16.0      farver_2.1.2         
## [88] memoise_2.0.1         htmltools_0.5.8.1     lifecycle_1.0.4      
## [91] httr_1.4.7            GlobalOptions_0.1.2   bit64_4.6.0-1        
## [94] MASS_7.3-65
\end{verbatim}

\subsection{Code Availability}\label{code-availability}

All analysis code is available in the project repository organized as
follows:

\begin{itemize}
\tightlist
\item
  \textbf{\texttt{scripts/00\_helper\_functions.R}}: Utility functions
  for file I/O, probability calculations
\item
  \textbf{\texttt{scripts/01\_data\_collection\_UPDATED.R}}: Data
  scraping, cleaning, and preparation
\item
  \textbf{\texttt{scripts/02\_bradley\_terry\_model.R}}: Bradley-Terry
  model fitting and team strength estimation
\item
  \textbf{\texttt{scripts/03\_seed\_analysis.R}}: Analytical probability
  calculations by seed
\item
  \textbf{\texttt{scripts/04\_tournament\_simulation.R}}: Monte Carlo
  tournament simulations (5,000 replications)
\item
  \textbf{\texttt{scripts/05\_visualization.R}}: Aggregate-level
  visualizations
\item
  \textbf{\texttt{scripts/06\_individual\_team\_probabilities.R}}:
  Individual team probability calculations
\item
  \textbf{\texttt{scripts/07\_individual\_team\_viz.R}}: Individual team
  visualizations
\end{itemize}

\subsection{Reproducibility}\label{reproducibility}

To reproduce this analysis:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Install required packages}
\FunctionTok{install.packages}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"tidyverse"}\NormalTok{, }\StringTok{"here"}\NormalTok{, }\StringTok{"BradleyTerry2"}\NormalTok{))}
\NormalTok{devtools}\SpecialCharTok{::}\FunctionTok{install\_github}\NormalTok{(}\StringTok{"sportsdataverse/wehoop"}\NormalTok{)}

\CommentTok{\# Run complete pipeline}
\FunctionTok{source}\NormalTok{(}\StringTok{"run\_all.R"}\NormalTok{)}

\CommentTok{\# Generate this report}
\NormalTok{rmarkdown}\SpecialCharTok{::}\FunctionTok{render}\NormalTok{(}\StringTok{"reports/final\_report.Rmd"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsection{Data Processing Details}\label{data-processing-details}

\subsubsection{Team Name
Standardization}\label{team-name-standardization}

Team names were standardized across games to ensure consistency:

\begin{itemize}
\tightlist
\item
  Removed trailing/leading whitespace
\item
  Standardized abbreviations (e.g., ``St.'' vs.~``State'')
\item
  Merged duplicate team entries
\end{itemize}

\subsubsection{Game Filtering}\label{game-filtering}

\begin{itemize}
\tightlist
\item
  \textbf{Included:} Regular season games only (September-February)
\item
  \textbf{Excluded:} Exhibition games, conference tournaments, NCAA
  tournament games, games with missing score data
\end{itemize}

\subsubsection{Seed Assignment}\label{seed-assignment}

For synthetic seeding:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Calculate win percentage for each team
\item
  Rank teams 1-64 by win\%
\item
  Assign seeds 1-16 in each of 4 regions using serpentine draft order
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\emph{Report generated: 2025-11-01}

\emph{Course: STAT 479 - Sports Analytics, University of
Wisconsin-Madison}

\end{document}
